'use strict';
const assert=require('node:assert/strict');const test=require('node:test');const{DATASETS,fingerprint,inspect,productionAdapter}=require('./learning-adoption-preflight');
const now='2026-09-25T00:00:00.000Z';
function source(){return{assignments:[{id:'a1',title:'Quiz',classId:'c1',createdById:'t1',type:'QUIZ',weight:1,totalMarks:10,allowLate:true,latePenaltyPct:0,maxAttempts:1,status:'DRAFT',randomizeQuestions:false,randomizeChoices:false,createdAt:now,updatedAt:now}],submissions:[{id:'s1',assignmentId:'a1',studentId:'st1',student:{userId:'u1'},status:'SUBMITTED',attemptNumber:1,submittedAt:now,createdAt:now,updatedAt:now}],quizQuestions:[{id:'q1',assignmentId:'a1',order:0,type:'ESSAY',prompt:'Why?',points:10,data:{},createdAt:now,updatedAt:now}],quizAnswers:[{id:'qa1',submissionId:'s1',questionId:'q1',response:{text:'Because'},autoGraded:false,createdAt:now,updatedAt:now}],courses:[{id:'c1',title:'Science',classId:'c1',createdById:'t1',status:'DRAFT',enrollmentOpen:false,createdAt:now,updatedAt:now}],lessons:[{id:'l1',courseId:'c1',title:'Intro',order:0,status:'DRAFT',gradingMode:'GRADED',showProgressBar:true,branchingEnabled:false,totalPoints:0,requireVideoWatch:false,videoWatchPct:90,maxAttempts:0,createdAt:now,updatedAt:now}],pages:[{id:'p1',lessonId:'l1',title:'Welcome',pageType:'CONTENT',content:{body:'Hi'},order:0,createdAt:now,updatedAt:now}],enrollments:[{id:'e1',courseId:'c1',studentId:'st1',student:{userId:'u1'},status:'ENROLLED',progressPct:0,enrolledAt:now}],attempts:[{id:'at1',lessonId:'l1',studentId:'st1',student:{userId:'u1'},status:'IN_PROGRESS',score:0,maxScore:0,startedAt:now}],responses:[{id:'r1',attemptId:'at1',pageId:'p1',answer:{viewed:true},answeredAt:now}],sessions:[{id:'cs1',courseId:'c1',lessonId:'l1',title:'Class',scheduledAt:now,durationMinutes:60,createdAt:now,updatedAt:now}],attendance:[{id:'ca1',sessionId:'cs1',studentId:'st1',student:{userId:'u1'},status:'PRESENT',source:'MANUAL',createdAt:now,updatedAt:now}],views:[{id:'v1',lessonId:'l1',studentId:'st1',student:{userId:'u1'},firstOpenedAt:now,lastOpenedAt:now,openCount:1,watchedSeconds:0,videoCompleted:false}]};}
function adapter(rows=source()){return{readSourceChunk:async(name,{after,limit})=>rows[name].filter((row)=>after===null||row.id>after).slice(0,limit),targetState:async(table)=>({table,exists:true,rowCount:0})};}
test('Learning preflight fingerprints all 13 datasets without emitting private payloads',async()=>{const report=await inspect(adapter(),{batchSize:1});assert.equal(report.ready,true);assert.equal(Object.keys(report.source.datasets).length,13);assert.match(report.source.sha256,/^[a-f0-9]{64}$/);assert.doesNotMatch(JSON.stringify(report),/Because|Welcome/);for(const{name}of DATASETS)assert.equal(report.source.datasets[name].count,1);});
test('Learning preflight is deterministic and read-only',async()=>{const a=await fingerprint(adapter().readSourceChunk,{batchSize:1}),b=await fingerprint(adapter().readSourceChunk,{batchSize:20});assert.equal(a.sha256,b.sha256);assert.deepEqual(a.datasets,b.datasets);});
test('Learning preflight blocks invalid relationships and occupied targets',async()=>{const rows=source();rows.responses[0].pageId='missing';const broken=adapter(rows);broken.targetState=async(table)=>({table,exists:true,rowCount:table.endsWith('_course')?1:0});const report=await inspect(broken);assert.equal(report.ready,false);assert(report.blockers.some((item)=>item.includes('invalid attempt/page relationship')));assert(report.blockers.some((item)=>item.includes('target table is not empty')));});
test('production adapter resolves LessonAttempt directory identity without a nonexistent relation',async()=>{let query;const prisma={lessonAttempt:{findMany:async(options)=>{query=options;return[{id:'at1',studentId:'st1'}];}},student:{findMany:async()=>[{id:'st1',userId:'u1'}]}};const rows=await productionAdapter(prisma).readSourceChunk('attempts',{after:null,limit:1});assert.equal(query.include,undefined);assert.deepEqual(rows,[{id:'at1',studentId:'st1',student:{id:'st1',userId:'u1'}}]);});
