'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),test=require('node:test');
const{DATASET,inspect}=require('./parent-portal-adoption-preflight');
const{adopt,databaseValue,dryRun,parseConfirmation}=require('./parent-portal-adopt');
const{drill,parseInput,routingRegistry}=require('./parent-portal-rollback-drill');
const now='2026-09-25T00:00:00.000Z',backupName='wattanam-20260925T030000Z.dump';
function rows(){return[{id:'r1',studentId:'student-profile-1',student:{userId:'student-user-1'},parentEmail:' Parent@Example.test ',parentName:'Parent One',parentPhone:'+85510000000',note:'Please link',status:'PENDING',rejectReason:null,createdAt:now,resolvedAt:null,resolvedBy:null},{id:'r2',studentId:'student-profile-2',student:{userId:'student-user-2'},parentEmail:'second@example.test',parentName:'Parent Two',parentPhone:null,note:null,status:'APPROVED',rejectReason:null,createdAt:now,resolvedAt:now,resolvedBy:'admin-1'}];}
function fixture(){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'wattanam-parent-portal-adopt-')),archive=path.join(directory,backupName);fs.writeFileSync(archive,'parent portal backup');const backupSha256=crypto.createHash('sha256').update(fs.readFileSync(archive)).digest('hex');fs.writeFileSync(archive.replace('.dump','.manifest.json'),JSON.stringify({format:'pg_dump-custom-v1',file:backupName,installationSlug:'bora-school',sizeBytes:fs.statSync(archive).size,sha256:backupSha256}));const source=rows(),target=new Map();let writes=0,crash=false;const chunk=(items,after,limit)=>items.filter(row=>after===null||row.id>after).slice(0,limit);const adapter={readSourceChunk:async(name,{after,limit})=>chunk(source,after,limit),readTargetChunk:async(name,{after,limit})=>chunk([...target.values()].sort((a,b)=>a.id.localeCompare(b.id)),after,limit),targetState:async table=>({table,exists:true,rowCount:target.size}),writeTargetChunk:async(name,items)=>{items.forEach(row=>target.set(row.id,{...row}));writes++;if(crash&&writes===1)throw new Error('simulated Parent Portal crash');}};return{directory,source,target,adapter,get writes(){return writes;},crash(value){crash=value;},close(){fs.rmSync(directory,{recursive:true,force:true});}};}
test('production values bind temporal columns as dates',()=>{assert.ok(databaseValue('createdAt',now) instanceof Date);assert.ok(databaseValue('resolvedAt',now) instanceof Date);assert.equal(databaseValue('resolvedAt',null),null);assert.equal(databaseValue('parentName','Parent One'),'Parent One');});
test('Parent Portal preflight blocks inconsistent resolution and missing directory identity',async()=>{const f=fixture();try{f.source[0].student={userId:null};f.source[1].resolvedBy=null;const report=await inspect(f.adapter);assert.equal(report.ready,false);assert.match(report.blockers.join('\n'),/no Student\.userId/);assert.match(report.blockers.join('\n'),/lacks resolution metadata/);assert.equal(JSON.stringify(report).includes('Please link'),false);}finally{f.close();}});
test('guarded Parent Portal dry-run is zero-write and requires exact confirmation',async()=>{const f=fixture();try{const pre=await inspect(f.adapter);assert.throws(()=>parseConfirmation({PARENT_PORTAL_ADOPTION_NON_INTERACTIVE:'true',PARENT_PORTAL_SCHOOL_SLUG:'bora-school',PARENT_PORTAL_CONFIRM_SLUG:'wrong',PARENT_PORTAL_SOURCE_SHA256:pre.source.sha256}),/exactly match/);const result=await dryRun({adapter:f.adapter,directory:f.directory,backupName,confirmation:{slug:'bora-school',sourceSha256:pre.source.sha256}});assert.equal(result.ready,true);assert.equal(result.zeroWriteGuarantee,true);assert.equal(f.writes,0);}finally{f.close();}});
test('Parent Portal adoption resumes a crash, reconciles exactly and rolls routing metadata back',async()=>{const f=fixture();try{const pre=await inspect(f.adapter),confirmation={slug:'bora-school',sourceSha256:pre.source.sha256};f.crash(true);await assert.rejects(adopt({adapter:f.adapter,directory:f.directory,backupName,confirmation,chunkSize:1}),/simulated/);f.crash(false);const result=await adopt({adapter:f.adapter,directory:f.directory,backupName,confirmation,chunkSize:1});assert.equal(result.stage,'reconciled');assert.equal(result.source.sha256,result.target.sha256);assert.equal(f.target.size,2);assert.equal(f.target.get('r1').studentDirectoryUserId,'student-user-1');assert.equal(f.target.get('r1').parentEmail,'parent@example.test');const registry=routingRegistry('plugin');const rolled=await drill({adapter:f.adapter,directory:f.directory,backupName,slug:'bora-school',registry});assert.equal(rolled.rolledBack,true);assert.deepEqual(registry,{routeOwner:'legacy',pluginEnabled:false});assert.equal(f.target.size,2);assert.throws(()=>parseInput({PARENT_PORTAL_SCHOOL_SLUG:'bora-school'}),/ROLLBACK_DRILL/);}finally{f.close();}});
test('Parent Portal adoption refuses a source changed after operator approval',async()=>{const f=fixture();try{const pre=await inspect(f.adapter);f.source.push({id:'r3',student:{userId:'student-user-3'},parentEmail:'third@example.test',status:'PENDING',createdAt:now,resolvedAt:null,resolvedBy:null});await assert.rejects(adopt({adapter:f.adapter,directory:f.directory,backupName,confirmation:{slug:'bora-school',sourceSha256:pre.source.sha256}}),/source fingerprint changed/);assert.equal(f.writes,0);}finally{f.close();}});
