import path from 'path';const plugin=require(path.resolve(__dirname,'../../../plugins/wattanam.communication/backend/index.js'));
describe('Communication plugin behavior',()=>{function activate(users=[{id:'parent-1',role:'PARENT'},{id:'student-1',role:'STUDENT'},{id:'teacher-1',role:'TEACHER'}]){const routes=new Map<string,any>(),database:any={query:jest.fn(),execute:jest.fn().mockResolvedValue({count:1})},directory={lookupUsers:jest.fn().mockResolvedValue(users),classesForUser:jest.fn().mockResolvedValue(['class-1']),getClassRoster:jest.fn().mockResolvedValue({classId:'class-1',students:[{studentId:'academic-1',userId:'student-1',parentId:'parent-1'}]})},realtime={notifyUser:jest.fn().mockResolvedValue(undefined)},jobs={register:jest.fn()},readModels={publish:jest.fn().mockResolvedValue(undefined)};database.transaction=jest.fn(async(work:any)=>work(database));plugin.activate({database,directory,jobs,realtime,readModels,permissions:{register:jest.fn()},navigation:{register:jest.fn()},routes:{register:(route:any)=>routes.set(`${route.method} ${route.path}`,route)}});return{routes,database,directory,realtime,jobs,readModels};}
  it('queues message delivery atomically and publishes content-free student activity',async()=>{const{routes,database,realtime,readModels}=activate();database.query.mockResolvedValueOnce([{totalCount:3,unreadCount:1,lastActivityAt:'2026-09-25T08:00:00.000Z'}]);const result=await routes.get('POST messages').handler({principal:{userId:'parent-1'},body:{receiverId:'student-1',content:'Hello'}});expect(result).toMatchObject({senderDirectoryUserId:'parent-1',receiverDirectoryUserId:'student-1',content:'Hello',deliveryQueued:true});expect(database.transaction).toHaveBeenCalledTimes(1);expect(database.execute.mock.calls[0][0]).toContain('plugin_wattanam_communication_message');expect(database.execute.mock.calls[1][0]).toContain('plugin_wattanam_communication_delivery_outbox');expect(realtime.notifyUser).not.toHaveBeenCalled();expect(readModels.publish).toHaveBeenCalledWith('student-communication-summary',1,'academic-1',expect.objectContaining({studentId:'academic-1',totalCount:3,unreadCount:1}));expect(JSON.stringify(readModels.publish.mock.calls[0][3])).not.toMatch(/content|sender|receiver|participant/);});
  it('delivers pending outbox events with a stable event ID',async()=>{const{database,realtime,jobs}=activate();database.query.mockResolvedValueOnce([{id:'event-1',messageId:'message-1',receiverDirectoryUserId:'student-1',attempts:0}]);const job=jobs.register.mock.calls[0][0];await job.handler();expect(realtime.notifyUser).toHaveBeenCalledWith('student-1','communication.message',{messageId:'message-1',eventId:'event-1'});expect(database.execute.mock.calls[0][0]).toContain('deliveredAt');});
  it('rejects an unrelated parent/student message',async()=>{const{routes,directory,database}=activate();directory.getClassRoster.mockResolvedValueOnce({classId:'class-1',students:[{studentId:'academic-2',userId:'other-student',parentId:'parent-1'}]});await expect(routes.get('POST messages').handler({principal:{userId:'parent-1'},body:{receiverId:'student-1',content:'Hello'}})).rejects.toThrow('not authorized');expect(database.execute).not.toHaveBeenCalled();});
  it('rejects peer parent messaging',async()=>{const{routes}=activate([{id:'parent-1',role:'PARENT'},{id:'parent-2',role:'PARENT'}]);await expect(routes.get('POST messages').handler({principal:{userId:'parent-1'},body:{receiverId:'parent-2',content:'Hello'}})).rejects.toThrow('cannot message each other');});
  it('scopes inbox and read mutations to the caller identity',async()=>{const{routes,database}=activate();database.query.mockResolvedValueOnce([]);await routes.get('GET messages/inbox').handler({principal:{userId:'parent-1'},query:{limit:'9999'}});expect(database.query.mock.calls[0][1]).toEqual(['parent-1',500]);await routes.get('PATCH messages/read/:partnerId').handler({principal:{userId:'parent-1'},params:{partnerId:'teacher-1'}});expect(database.execute.mock.calls[0][1]).toEqual(['teacher-1','parent-1']);});
  it('validates and persists bounded post content',async()=>{const{routes,database}=activate();const result=await routes.get('POST posts').handler({principal:{userId:'admin-1'},body:{title:'School news',type:'image',tags:['news','news'],published:true}});expect(result).toMatchObject({title:'School news',type:'IMAGE',tags:['news']});expect(database.execute.mock.calls[0][0]).toContain('plugin_wattanam_communication_post');});
});
