'use client';

import { useEffect, useState } from 'react';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type Session = { session: number; scope: 'STUDENT' | 'STAFF'; type: 'CHECK_IN' | 'CHECK_OUT'; startTime: string; endTime: string; classId?: string };
type Settings = { classFormat: string; classFormatRules: boolean; staffFormatRules: boolean; staffWorkingDays: string[] };

const classDefaults: Session[] = [
  { scope: 'STUDENT', session: 1, type: 'CHECK_IN', startTime: '07:00', endTime: '07:15' },
  { scope: 'STUDENT', session: 2, type: 'CHECK_OUT', startTime: '12:00', endTime: '12:15' },
  { scope: 'STUDENT', session: 3, type: 'CHECK_IN', startTime: '13:00', endTime: '13:15' },
  { scope: 'STUDENT', session: 4, type: 'CHECK_OUT', startTime: '17:00', endTime: '17:15' },
];
const staffDefaults: Session[] = [
  { scope: 'STAFF', session: 1, type: 'CHECK_IN', startTime: '07:00', endTime: '07:30' },
  { scope: 'STAFF', session: 2, type: 'CHECK_OUT', startTime: '11:30', endTime: '12:00' },
  { scope: 'STAFF', session: 3, type: 'CHECK_IN', startTime: '13:00', endTime: '13:30' },
  { scope: 'STAFF', session: 4, type: 'CHECK_OUT', startTime: '17:00', endTime: '17:30' },
];
const presets: Array<{ id: string; icon: string; label: string; detail: string; sessions: Array<[string, string]> }> = [
  { id: 'FULL', icon: '🌞', label: 'Full Day', detail: '7:00 AM – 5:00 PM (Morning + Afternoon)', sessions: [['07:00','07:15'],['12:00','12:15'],['13:00','13:15'],['17:00','17:15']] },
  { id: 'MORNING', icon: '🌅', label: 'Morning Only', detail: '7:00 AM – 12:00 PM', sessions: [['07:00','07:15'],['12:00','12:15'],['12:00','12:15'],['12:00','12:15']] },
  { id: 'AFTERNOON', icon: '🌤️', label: 'Afternoon Only', detail: '1:00 PM – 5:30 PM', sessions: [['13:00','13:15'],['13:00','13:15'],['13:00','13:15'],['17:15','17:30']] },
  { id: 'EVENING', icon: '🌆', label: 'Evening', detail: '6:00 PM – 9:00 PM', sessions: [['18:00','18:15'],['18:00','18:15'],['20:45','21:00'],['20:45','21:00']] },
  { id: 'NIGHT', icon: '🌙', label: 'Night Shift', detail: '6:00 PM – 6:00 AM (overnight)', sessions: [['18:00','18:15'],['23:45','23:59'],['00:00','00:15'],['05:45','06:00']] },
  { id: 'CUSTOM', icon: '🔧', label: 'Custom', detail: 'Set times manually', sessions: [] },
];
const names = ['Morning 1', 'Morning 2', 'Afternoon 1', 'Afternoon 2'];
const days = ['MON','TUE','WED','THU','FRI','SAT','SUN'];
function rows(value: unknown): any[] { return Array.isArray(value) ? value : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function normalize(value: unknown, scope: 'STUDENT' | 'STAFF', fallback: Session[]) { const found = rows(value).filter((item) => item.scope === scope && !item.classId); return fallback.map((item) => { const current = found.find((candidate) => Number(candidate.session) === item.session); return current ? { ...item, ...current, startTime: String(current.startTime).slice(0,5), endTime: String(current.endTime).slice(0,5) } : { ...item }; }); }

export default function PluginSessionManager({ pluginId, value, data, sources, options, loading, error, onRefresh }: any) {
  const [tab, setTab] = useState<'STUDENT' | 'STAFF'>('STUDENT'); const [student, setStudent] = useState(classDefaults); const [staff, setStaff] = useState(staffDefaults);
  const [settings, setSettings] = useState<Settings>({ classFormat: 'CUSTOM', classFormatRules: false, staffFormatRules: false, staffWorkingDays: ['MON','TUE','WED','THU','FRI'] });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [saveError, setSaveError] = useState('');
  useEffect(() => { setStudent(normalize(value, 'STUDENT', classDefaults)); setStaff(normalize(value, 'STAFF', staffDefaults)); }, [value]);
  useEffect(() => { const incoming = data[options.settingsSource]; if (incoming && typeof incoming === 'object') setSettings((current) => ({ ...current, ...(incoming as Settings) })); }, [data, options.settingsSource]);
  const getSource = (id: string) => sources.find((item: Source) => item.id === id) as Source | undefined;
  async function request(sourceId: string, body: unknown) { const source = getSource(sourceId); if (!source) throw new Error('This action is unavailable.'); const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${source.path}`, { method: source.method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(Array.isArray(result.message) ? result.message.join(' ') : result.message || `Request failed (${response.status})`); return result; }
  const active = tab === 'STUDENT' ? student : staff; const setActive = tab === 'STUDENT' ? setStudent : setStaff;
  function update(index: number, change: Partial<Session>) { setActive(active.map((item, itemIndex) => itemIndex === index ? { ...item, ...change } : item)); if (tab === 'STUDENT') setSettings({ ...settings, classFormat: 'CUSTOM' }); }
  function applyPreset(id: string) { const preset = presets.find((item) => item.id === id); if (!preset) return; setSettings({ ...settings, classFormat: id }); if (preset.sessions.length) setStudent(classDefaults.map((item, index) => ({ ...item, startTime: preset.sessions[index][0], endTime: preset.sessions[index][1] }))); }
  async function save() { setBusy(true); setSaveError(''); setMessage(''); try { for (const item of active) { if (!/^\d{2}:\d{2}$/.test(item.startTime) || !/^\d{2}:\d{2}$/.test(item.endTime)) throw new Error(`Session ${item.session} requires valid start and end times.`); await request(options.saveSessionSource, { ...item, classId: '' }); } await request(options.saveSettingsSource, settings); setMessage(`${tab === 'STUDENT' ? 'Class' : 'Staff'} session settings saved.`); await onRefresh(); } catch (cause) { setSaveError(cause instanceof Error ? cause.message : 'Settings could not be saved.'); } finally { setBusy(false); } }
  function reset() { if (tab === 'STUDENT') { setStudent(classDefaults.map((item) => ({ ...item }))); setSettings({ ...settings, classFormat: 'FULL', classFormatRules: false }); } else { setStaff(staffDefaults.map((item) => ({ ...item }))); setSettings({ ...settings, staffFormatRules: false, staffWorkingDays: ['MON','TUE','WED','THU','FRI'] }); } setMessage('Defaults restored locally. Select Save to persist them.'); }
  return <section className="space-y-6 rounded-3xl bg-white p-1 sm:p-2">
    <header><h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Session Time Settings</h1><p className="mt-1 text-sm text-slate-500">Configure time windows</p></header>
    <div className="inline-flex rounded-xl bg-slate-100 p-1"><button onClick={() => setTab('STUDENT')} className={`rounded-lg px-5 py-2 text-sm font-semibold ${tab === 'STUDENT' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Class Sessions</button><button onClick={() => setTab('STAFF')} className={`rounded-lg px-5 py-2 text-sm font-semibold ${tab === 'STAFF' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>Staff Sessions</button></div>
    <div><p className="text-sm text-slate-500">{tab === 'STUDENT' ? 'Configure global default time windows for student class attendance. Teachers can override these per-class.' : 'Configure time windows for staff check-in and check-out sessions.'}</p><span className="mt-4 inline-flex rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2 text-xs font-medium text-indigo-700">🏢 Admin scope: Global organization</span></div>
    {message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}{saveError && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{saveError}</div>}{error && <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
    {tab === 'STUDENT' && <div><h2 className="text-sm font-bold text-slate-700">Quick Presets — Choose Attendance Format</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{presets.map((preset) => <button key={preset.id} onClick={() => applyPreset(preset.id)} className={`min-h-28 rounded-2xl border p-4 text-left transition ${settings.classFormat === preset.id ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100' : 'border-slate-200 bg-slate-50 hover:border-indigo-300'}`}><span className="text-xl">{preset.icon}</span><strong className="mt-3 block text-sm text-slate-900">{preset.label}</strong><span className="mt-1 block text-xs text-slate-500">{preset.detail}</span>{settings.classFormat === preset.id && <span className="mt-2 block text-xs font-bold text-indigo-600">✓ Active</span>}</button>)}</div></div>}
    {loading ? <div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map((item) => <div key={item} className="h-44 animate-pulse rounded-2xl bg-slate-100" />)}</div> : <div className="grid gap-4 md:grid-cols-2">{active.map((item, index) => <article key={item.session} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl text-white ${item.type === 'CHECK_IN' ? 'bg-emerald-500' : 'bg-blue-600'}`}>📥</span><div><h2 className="font-bold text-slate-900">{names[index]}</h2><p className="text-xs text-slate-500">Session {item.session}</p></div></div><label className="mt-4 block text-xs font-medium text-slate-600">Type<select value={item.type} onChange={(event) => update(index, { type: event.target.value as Session['type'] })} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option value="CHECK_IN">📥 Check-In</option><option value="CHECK_OUT">📤 Check-Out</option></select></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-medium text-slate-600">Start Time<input type="time" value={item.startTime} onChange={(event) => update(index, { startTime: event.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="text-xs font-medium text-slate-600">End Time<input type="time" value={item.endTime} onChange={(event) => update(index, { endTime: event.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div></article>)}</div>}
    <div className="flex items-center justify-between rounded-2xl border border-slate-200 p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-orange-500 to-pink-500 text-white">📊</span><div><h2 className="font-bold text-slate-900">Attendance Format Rules</h2><p className="text-xs text-slate-500">Convert accumulated lates/permissions into absences for {tab === 'STUDENT' ? 'student' : 'staff'} reports</p></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={tab === 'STUDENT' ? settings.classFormatRules : settings.staffFormatRules} onChange={(event) => setSettings({ ...settings, [tab === 'STUDENT' ? 'classFormatRules' : 'staffFormatRules']: event.target.checked })} className="h-5 w-5 accent-indigo-600" />{(tab === 'STUDENT' ? settings.classFormatRules : settings.staffFormatRules) ? 'Enabled' : 'Disabled'}</label></div>
    {tab === 'STAFF' && <div className="rounded-2xl border border-slate-200 p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">🗓️ Staff Weekly Schedule</h2><p className="mt-1 text-xs text-slate-500">Mark days when staff are not expected to work. Days off are excluded from attendance reports.</p></div><button onClick={() => setSettings({ ...settings, staffWorkingDays: ['MON','TUE','WED','THU','FRI'] })} className="text-xs text-slate-600">↩ Reset</button></div><div className="mt-4 flex flex-wrap gap-2">{days.map((day) => { const working = settings.staffWorkingDays.includes(day); return <button key={day} onClick={() => setSettings({ ...settings, staffWorkingDays: working ? settings.staffWorkingDays.filter((item) => item !== day) : [...settings.staffWorkingDays, day] })} className={`rounded-xl border px-4 py-2 text-sm ${working ? 'border-emerald-300 bg-emerald-50 text-emerald-700' : 'border-red-300 bg-red-50 text-red-600'}`}>{day[0] + day.slice(1).toLowerCase()} {working ? '✓ Working' : '⊘ Off'}</button>; })}</div><div className="mt-3 flex gap-2"><button onClick={() => setSettings({ ...settings, staffWorkingDays: ['MON','TUE','WED','THU','FRI'] })} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs">Mon–Fri</button><button onClick={() => setSettings({ ...settings, staffWorkingDays: ['MON','TUE','WED','THU','FRI','SAT'] })} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs">Mon–Sat</button><button onClick={() => setSettings({ ...settings, staffWorkingDays: [...days] })} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs">All 7 days</button></div></div>}
    <div className="flex flex-wrap gap-4"><button disabled={busy} onClick={() => void save()} className="rounded-xl bg-indigo-600 px-6 py-3 font-bold text-white shadow-lg shadow-indigo-200 disabled:opacity-60">💾 {busy ? 'Saving…' : `Save ${tab === 'STUDENT' ? 'Class' : 'Staff'} Settings`}</button><button onClick={reset} className="rounded-xl px-5 py-3 font-semibold text-slate-600">↩ Reset to Default</button></div><div className="border-t border-slate-200 pt-2"><p className="text-xs text-slate-400">Additional identifier, holiday, and alert configuration continues below.</p></div>
  </section>;
}
