'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type RecordRow = { personId: string; personNameSnapshot?: string; personNumberSnapshot?: string; classNameSnapshot?: string; date: string; session: number; status: string; permissionType?: string; checkInTime?: string; checkOutTime?: string };
type Person = { id: string; name?: string; nameKh?: string; studentNumber?: string; employeeNumber?: string; address?: string; position?: string; department?: { name?: string }; user?: { name?: string } };
type Session = { session: number; scope: string; type: string; startTime: string; endTime: string; classId?: string };
type View = 'daily' | 'weekly' | 'monthly' | 'yearly';
function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function pathOf(source: Source, params: Record<string, string>) { return source.path.replace(/:([a-zA-Z][a-zA-Z0-9_]*)/g, (_, key) => encodeURIComponent(params[key] || '')); }
function iso(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function name(person: Person) { return person.nameKh || person.name || person.user?.name || 'Unknown'; }
function csvCell(value: unknown) { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }

export default function PluginAttendanceReportManager({ pluginId, value, data, sources, options, loading, error }: any) {
  const mode = options.mode === 'staff' ? 'staff' : 'student'; const classes = useMemo(() => mode === 'student' ? rows<any>(value) : [], [mode, value]); const staff = useMemo(() => mode === 'staff' ? rows<Person>(value) : [], [mode, value]);
  const allSessions = rows<Session>(data[options.sessionsSource]); const [classId, setClassId] = useState(''); const [date, setDate] = useState(iso(new Date())); const [view, setView] = useState<View>('daily');
  const [people, setPeople] = useState<Person[]>([]); const [records, setRecords] = useState<RecordRow[]>([]); const [busy, setBusy] = useState(false); const [reportError, setReportError] = useState(''); const [printOpen, setPrintOpen] = useState(false); const [preview, setPreview] = useState(false);
  const [authoritative, setAuthoritative] = useState<any>(null);
  const [paper, setPaper] = useState('A4'); const [organization, setOrganization] = useState('Wattanam School'); const [headerLines, setHeaderLines] = useState(['Attendance Report']); const [signers, setSigners] = useState(['Teacher', 'Admin']);
  const getSource = useCallback((id: string) => sources.find((item: Source) => item.id === id) as Source | undefined, [sources]);
  const request = useCallback(async (id: string, params: Record<string,string> = {}, query: Record<string,string> = {}) => { const source = getSource(id); if (!source) throw new Error('Report source is unavailable.'); const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${pathOf(source, params)}?${new URLSearchParams(query)}`); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || `Report request failed (${response.status})`); return result; }, [getSource, pluginId]);
  useEffect(() => { if (mode === 'student' && !classId && classes.length) setClassId(classes[0].id); }, [classId, classes, mode]);
  const period = useMemo(() => { const current = new Date(`${date}T12:00:00`); if (view === 'daily') return { start: date, end: date }; if (view === 'weekly') { const day = (current.getDay()+6)%7; const start = new Date(current); start.setDate(current.getDate()-day); const end = new Date(start); end.setDate(start.getDate()+6); return { start: iso(start), end: iso(end) }; } if (view === 'monthly') return { start: `${date.slice(0,7)}-01`, end: iso(new Date(current.getFullYear(), current.getMonth()+1, 0)) }; return { start: `${current.getFullYear()}-01-01`, end: `${current.getFullYear()}-12-31` }; }, [date, view]);
  const load = useCallback(async () => { if (mode === 'student' && !classId) return; setBusy(true); setReportError(''); try { const report = await request(options.authoritativeSource, {}, { ...(mode === 'student' ? { classId } : {}), startDate: period.start, endDate: period.end }); setAuthoritative(report); setPeople(rows<Person>(report.people)); setRecords(rows<RecordRow>(report.entries)); } catch (cause) { setReportError(cause instanceof Error ? cause.message : 'Report could not be loaded.'); } finally { setBusy(false); } }, [classId, mode, options.authoritativeSource, period.end, period.start, request]);
  useEffect(() => { void load(); }, [load]);
  const scope = mode === 'staff' ? 'STAFF' : 'STUDENT'; const sessions = allSessions.filter((item) => item.scope === scope && (!item.classId || item.classId === classId)).sort((a,b) => a.session-b.session).slice(0,4);
  const recordMap = useMemo(() => new Map(records.map((item) => [`${item.personId}:${item.session}:${String(item.date).slice(0,10)}`, item])), [records]);
  const dailyRows = people.map((person) => ({ person, records: [1,2,3,4].map((session) => recordMap.get(`${person.id}:${session}:${date}`)) }));
  const totals = useMemo(() => authoritative?.totals || ({ present: 0, late: 0, absent: 0, permission: 0, expected: 0 }), [authoritative]);
  function move(days: number) { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate()+days); setDate(iso(next)); }
  function exportCsv() { const lines = [['Date','ID','Name','Session','Status'], ...records.map((item) => [String(item.date).slice(0,10),item.personNumberSnapshot,item.personNameSnapshot,item.session,item.status])].map((line) => line.map(csvCell).join(',')); const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'})); const anchor=document.createElement('a'); anchor.href=url; anchor.download=`${mode}-attendance-${period.start}-${period.end}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  const statusMark = (record?: RecordRow) => !record ? <span className="text-red-400">✗</span> : record.status === 'PRESENT' ? <span className="font-bold text-emerald-600">✓</span> : record.status === 'LATE' ? <span className="font-bold text-amber-500">L</span> : record.status === 'PERMISSION' ? <span className="font-bold text-blue-500">P</span> : <span className="text-red-400">✗</span>;
  const reportTable = <table className="min-w-full border-collapse text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-500 print:bg-slate-800 print:text-white"><tr><th className="px-4 py-3">Day</th><th className="px-4 py-3">ID</th><th className="px-4 py-3">{mode === 'staff' ? 'Staff Name' : 'Student Name'}</th><th className="px-4 py-3">{mode === 'staff' ? 'Department' : 'Address'}</th>{[1,2,3,4].map((number) => { const session=sessions.find((item)=>Number(item.session)===number); return <th key={number} className="px-3 py-3 text-center">{session?.type?.replace('_','-') || `Session ${number}`}<span className="block text-[10px] font-normal normal-case text-slate-400">{session ? `${session.startTime.slice(0,5)}–${session.endTime.slice(0,5)}` : ''}</span></th>; })}<th className="px-3 py-3 text-center">Permission</th></tr></thead><tbody className="divide-y">{dailyRows.map(({person,records: personRecords}) => <tr key={person.id} className="even:bg-slate-50"><td className="px-4 py-3">{new Date(`${date}T12:00`).toLocaleDateString(undefined,{weekday:'short'})}</td><td className="px-4 py-3 font-mono text-xs">{person.studentNumber || person.employeeNumber || person.id.slice(0,8)}</td><td className="px-4 py-3 font-semibold">{name(person)}</td><td className="px-4 py-3 text-slate-500">{person.address || person.department?.name || person.position || '—'}</td>{personRecords.map((record,index)=><td key={index} className="px-3 py-3 text-center">{statusMark(record)}</td>)}<td className="px-3 py-3 text-center text-blue-500">{personRecords.some((item)=>item?.status==='PERMISSION')?'P':'—'}</td></tr>)}</tbody></table>;
  if (preview) return <div className="fixed inset-0 z-[100] overflow-auto bg-slate-200"><header className="sticky top-0 flex items-center justify-between bg-white p-3 shadow print:hidden"><button onClick={()=>setPreview(false)} className="rounded-lg bg-slate-100 px-4 py-2">← Close</button><span>{mode === 'student' ? classes.find((item)=>item.id===classId)?.name : 'Staff'} — {view} — {paper}</span><button onClick={()=>window.print()} className="rounded-lg bg-indigo-600 px-5 py-2 font-bold text-white">🖨 Print Report</button></header><main className="mx-auto my-8 min-h-[297mm] max-w-[210mm] bg-white p-12 shadow print:m-0 print:max-w-none print:shadow-none"><div className="text-center"><strong>{organization}</strong>{headerLines.map((line,index)=><p key={index}>{line}</p>)}<h1 className="mt-5 text-xl font-bold">Attendance Report</h1><p className="mt-2 text-sm">Report: {view} &nbsp; Period: {period.start}{period.end!==period.start?` – ${period.end}`:''}</p></div><div className="mt-8 overflow-hidden border">{reportTable}</div><footer className="mt-12 flex justify-around text-center">{signers.map((signer)=><div key={signer}><div className="h-14" /><div className="w-36 border-t pt-2 text-xs">{signer}</div></div>)}</footer></main></div>;
  return <section className="space-y-6"><header><h1 className="text-3xl font-extrabold text-slate-900">Attendance Reports</h1><p className="mt-1 text-sm text-slate-500">Cambodia Time (GMT+7) · {mode === 'staff' ? 'Staff' : 'Student'} attendance</p></header>{(error||reportError)&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error||reportError}</p>}
    <div className="flex flex-wrap items-end gap-4 rounded-2xl border bg-white p-5 shadow-sm">{mode==='student'&&<label className="text-xs font-semibold">Class<select value={classId} onChange={(event)=>setClassId(event.target.value)} className="mt-2 block rounded-xl border px-4 py-2.5">{classes.map((item)=><option key={item.id} value={item.id}>{item.name}{item.subject?` — ${item.subject}`:''}</option>)}</select></label>}<label className="text-xs font-semibold">Date<div className="mt-2 flex gap-2"><button onClick={()=>move(-1)} className="rounded-lg border px-3">◀</button><input type="date" value={date} onChange={(event)=>setDate(event.target.value)} className="rounded-xl border px-4 py-2.5"/><button onClick={()=>move(1)} className="rounded-lg border px-3">▶</button><button onClick={()=>setDate(iso(new Date()))} className="rounded-lg border px-3">📅 Today</button></div></label><div className="ml-auto flex gap-2"><button onClick={()=>setPrintOpen(true)} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">🖨 Print Report</button><button onClick={exportCsv} className="rounded-xl bg-purple-600 px-5 py-3 font-bold text-white">📊 Export Report</button></div><p className="w-full text-sm font-semibold">{new Date(`${date}T12:00`).toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</p></div>
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap gap-2">{sessions.map((session)=><span key={session.session} className="rounded-lg border bg-slate-50 px-3 py-2 text-xs"><b className={session.type==='CHECK_IN'?'text-emerald-600':'text-red-500'}>● {session.type.replace('_','-')}</b> {session.startTime.slice(0,5)}–{session.endTime.slice(0,5)}</span>)}{authoritative?.excludedHolidays?.length>0&&<span className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700">{authoritative.excludedHolidays.length} holiday(s) excluded</span>}<span className="rounded-lg bg-indigo-50 px-3 py-2 text-xs text-indigo-700">{totals.expected || 0} elapsed expected sessions</span></div></div>
    <div className="grid grid-cols-4 border-b">{(['daily','weekly','monthly','yearly'] as View[]).map((item)=><button key={item} onClick={()=>setView(item)} className={`border-b-2 p-4 capitalize ${view===item?'border-indigo-600 text-indigo-600':'border-transparent text-slate-500'}`}>{item==='daily'?'📋':item==='weekly'?'🗓️':item==='monthly'?'📅':'📊'} {item}</button>)}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[[mode==='staff'?'TOTAL STAFF':'TOTAL STUDENTS',people.length],['PRESENT',totals.present],['PRESENT (LATE)',totals.late],['ABSENT',totals.absent],['PERMISSION',totals.permission]].map(([label,count],index)=><div key={String(label)} className="rounded-2xl border-t-4 border-cyan-400 bg-white p-5 shadow-sm"><span className="text-xs font-semibold text-slate-500">{label}</span><strong className="mt-2 block text-3xl">{count}</strong></div>)}</div>
    <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm">{busy||loading?<p className="p-12 text-center text-slate-400">Loading report…</p>:view==='daily'?reportTable:<table className="min-w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-4">Date</th><th className="p-4">ID</th><th className="p-4">Name</th><th className="p-4">Session</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y">{records.map((item,index)=><tr key={`${item.personId}-${item.date}-${item.session}-${index}`}><td className="p-4">{String(item.date).slice(0,10)}</td><td className="p-4">{item.personNumberSnapshot}</td><td className="p-4 font-semibold">{item.personNameSnapshot}</td><td className="p-4">{item.session}</td><td className="p-4">{item.status}</td></tr>)}</tbody></table>}</div>
    {printOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={(event)=>{event.preventDefault();setPrintOpen(false);setPreview(true);}} className="max-h-[90vh] w-full max-w-md overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-bold">🖨 Print Attendance Report</h2><p className="text-xs text-slate-500">Select options and print report</p></div><button type="button" onClick={()=>setPrintOpen(false)}>×</button></div><label className="mt-5 block text-xs font-semibold">Paper Size<select value={paper} onChange={(event)=>setPaper(event.target.value)} className="mt-2 w-full rounded-lg border p-2"><option>A4</option><option>Letter</option><option>Legal</option></select></label><label className="mt-4 block text-xs font-semibold">Organization Name<input value={organization} onChange={(event)=>setOrganization(event.target.value)} className="mt-2 w-full rounded-lg border p-2"/></label><label className="mt-4 block text-xs font-semibold">Header Lines<textarea value={headerLines.join('\n')} onChange={(event)=>setHeaderLines(event.target.value.split('\n'))} className="mt-2 w-full rounded-lg border p-2"/></label><label className="mt-4 block text-xs font-semibold">Signers<input value={signers.join(', ')} onChange={(event)=>setSigners(event.target.value.split(',').map((item)=>item.trim()).filter(Boolean))} className="mt-2 w-full rounded-lg border p-2"/></label><div className="mt-5 rounded-xl bg-slate-50 p-3 text-xs"><b>Export Preview</b><p>Period: {period.start} – {period.end}</p><p>Paper: {paper}</p></div><div className="mt-5 flex gap-2"><button type="button" onClick={()=>setPrintOpen(false)} className="flex-1 rounded-lg border p-2">Cancel</button><button className="flex-1 rounded-lg bg-emerald-600 p-2 font-bold text-white">Preview & Print</button></div></form></div>}
  </section>;
}
