'use client';

import { useEffect, useMemo, useState } from 'react';
import QRCode from 'qrcode';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type Person = { id: string; name?: string; nameKh?: string; studentNumber?: string; employeeNumber?: string; position?: string; photo?: string; phone?: string; email?: string; qrCode?: string; dateOfBirth?: string; address?: string; user?: { name?: string; email?: string; phone?: string; photo?: string } };
type ClassRow = { id: string; name: string; subject?: string; studentCount?: number; teacher?: { name?: string }; studyYearId?: string; studyYear?: { id: string; label?: string; isCurrent?: boolean } };
function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function pathOf(source: Source, params: Record<string, string>) { return source.path.replace(/:([a-zA-Z][a-zA-Z0-9_]*)/g, (_, key) => encodeURIComponent(params[key] || '')); }
function personName(person: Person) { return person.nameKh || person.name || person.user?.name || 'Unnamed'; }

function IdentityCard({ person, subtitle, year }: { person: Person; subtitle: string; year?: string }) {
  const [qr, setQr] = useState(''); const code = person.qrCode || '';
  useEffect(() => { let alive = true; if (!code) { setQr(''); return; } QRCode.toDataURL(code, { width: 320, margin: 1, errorCorrectionLevel: 'M' }).then((value) => { if (alive) setQr(value); }); return () => { alive = false; }; }, [code]);
  const photo = person.photo || person.user?.photo; const number = person.studentNumber || person.employeeNumber || person.id.slice(0, 8);
  function downloadQr() { if (!qr) return; const anchor = document.createElement('a'); anchor.href = qr; anchor.download = `${number}-attendance-qr.png`; anchor.click(); }
  return <article className="break-inside-avoid overflow-hidden rounded-2xl border-2 border-indigo-600 bg-gradient-to-b from-indigo-50 to-white shadow-sm print:shadow-none"><header className="bg-gradient-to-r from-indigo-700 via-purple-600 to-rose-500 px-4 py-3 text-center text-white"><strong className="block text-sm">Wattanam School</strong><span className="text-xs">Official Identification Card</span></header><div className="relative min-h-64 p-4"><div className="flex items-start gap-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-full border-4 border-indigo-500 bg-indigo-100 text-4xl font-bold text-indigo-500">{photo ? <img src={photo} alt="" className="h-full w-full object-cover" /> : personName(person)[0]}</div><div className="min-w-0"><h2 className="truncate text-xl font-extrabold text-slate-900">{personName(person)}</h2><p className="font-mono text-sm text-indigo-600">ID: {number}</p><p className="mt-2 text-sm font-semibold text-rose-600">{subtitle}</p>{year && <p className="text-xs text-slate-500">Study year: {year}</p>}<p className="mt-1 text-xs text-slate-500">{person.position || person.dateOfBirth || person.user?.phone || person.phone || ''}</p></div></div><div className="mt-5 flex items-end justify-between gap-3"><div className="text-xs text-slate-500"><p>{person.address || person.user?.email || person.email || ''}</p><p className="mt-3 font-semibold text-indigo-700">Scan for attendance</p></div>{qr ? <img src={qr} alt={`Attendance QR for ${personName(person)}`} className="h-28 w-28 rounded-lg border bg-white p-1" /> : <div className="flex h-28 w-28 items-center justify-center rounded-lg border border-red-200 bg-red-50 p-2 text-center text-xs text-red-600">QR identifier is missing</div>}</div></div><footer className="flex gap-2 border-t bg-white p-2 print:hidden"><button onClick={downloadQr} disabled={!qr} className="flex-1 rounded-lg border px-3 py-2 text-xs font-semibold disabled:opacity-40">↓ QR PNG</button><button onClick={() => window.print()} className="flex-1 rounded-lg border border-indigo-200 px-3 py-2 text-xs font-semibold text-indigo-700">Print / PDF</button></footer></article>;
}

export default function PluginIdCardManager({ pluginId, value, data, sources, options, loading, error }: any) {
  const mode = options.mode === 'staff' ? 'staff' : 'student'; const classes = useMemo(() => rows<ClassRow>(value), [value]); const years = rows<any>(data[options.studyYearsSource]);
  const staff = rows<Person>(value); const [classId, setClassId] = useState(''); const [yearId, setYearId] = useState(''); const [students, setStudents] = useState<Person[]>([]); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [loadError, setLoadError] = useState('');
  const currentYear = years.find((item) => item.isCurrent)?.id || years[0]?.id || '';
  useEffect(() => { if (!yearId && currentYear) setYearId(currentYear); }, [currentYear, yearId]);
  const visibleClasses = classes.filter((item) => !yearId || item.studyYearId === yearId); const selectedClass = classes.find((item) => item.id === classId); const selectedYear = years.find((item) => item.id === (selectedClass?.studyYearId || yearId));
  async function openClass(id: string) { const source = sources.find((item: Source) => item.id === options.studentsSource) as Source | undefined; if (!source) return; setBusy(true); setLoadError(''); try { const ensure = sources.find((item: Source) => item.id === options.ensureSource) as Source | undefined; if (ensure) { const ensured = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${pathOf(ensure, { classId: id })}`, { method: ensure.method, headers: { 'Content-Type': 'application/json' }, body: '{}' }); if (!ensured.ok) { const detail = await ensured.json().catch(() => ({})); throw new Error(detail.message || 'Student card identifiers could not be prepared.'); } } const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${pathOf(source, { classId: id })}`); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Students could not be loaded.'); setStudents(rows<Person>(result)); setClassId(id); } catch (cause) { setLoadError(cause instanceof Error ? cause.message : 'Students could not be loaded.'); } finally { setBusy(false); } }
  const people = (mode === 'staff' ? staff : students).filter((item) => `${personName(item)} ${item.studentNumber || ''} ${item.employeeNumber || ''} ${item.position || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4 print:hidden"><div><h1 className="text-3xl font-extrabold text-slate-900">{mode === 'staff' ? '👥 Staff ID Cards' : '🎓 Student ID Cards'}</h1><p className="mt-1 text-sm text-slate-500">{mode === 'staff' ? `${staff.length} staff members` : `${selectedYear?.label || 'Current study year'} · ${visibleClasses.length} classes · ${visibleClasses.reduce((sum, item) => sum + Number(item.studentCount || 0), 0)} students`}</p></div>{mode === 'student' && <select value={yearId} onChange={(event) => { setYearId(event.target.value); setClassId(''); setStudents([]); }} className="rounded-xl border px-4 py-3">{years.map((item) => <option key={item.id} value={item.id}>{item.label || item.year}{item.isCurrent ? ' (Current)' : ''}</option>)}</select>}</header>
    {(error || loadError) && <p className="rounded-xl bg-red-50 p-4 text-red-700">{error || loadError}</p>}
    {mode === 'student' && !classId && <><div className="flex items-center justify-between print:hidden"><h2 className="text-lg font-bold">📖 All Classes in {selectedYear?.label || 'Study Year'}</h2><button onClick={() => window.print()} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">▣ Download All Cards</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{visibleClasses.map((item) => <button key={item.id} onClick={() => void openClass(item.id)} className="overflow-hidden rounded-2xl border text-left shadow-sm"><div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-5 text-white"><span className="float-right rounded-full bg-white/20 px-3 py-1 text-xs font-bold">{item.studentCount || 0} students</span><span className="text-2xl">📖</span><h3 className="mt-4 text-lg font-bold">{item.name}</h3></div><div className="flex justify-between p-4 text-sm"><span>♟ {item.teacher?.name || 'No teacher'}</span><span className="text-indigo-600">View →</span></div></button>)}</div></>}
    {(mode === 'staff' || classId) && <><div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4 shadow-sm print:hidden">{mode === 'student' && <button onClick={() => { setClassId(''); setStudents([]); }} className="text-indigo-600">← Back to Classes</button>}<div className="min-w-52 flex-1"><strong>{mode === 'staff' ? 'All Staff' : selectedClass?.name}</strong><p className="text-xs text-slate-500">{people.length} cards ready</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${mode === 'staff' ? 'staff' : 'students'}…`} className="rounded-xl border px-4 py-2.5" /><button onClick={() => window.print()} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">▣ Download / Print Cards ({people.length})</button></div>{busy || loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="h-96 animate-pulse rounded-2xl bg-slate-100" />)}</div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4 print:grid-cols-2">{people.map((person) => <IdentityCard key={person.id} person={person} subtitle={mode === 'staff' ? person.position || 'Staff' : selectedClass?.name || 'Student'} year={mode === 'student' ? selectedYear?.label : undefined} />)}</div>}</>}
  </section>;
}
