'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { BrowserMultiFormatReader } from '@zxing/library';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type ClassRow = { id: string; name: string; subject?: string; schedule?: string };
type Student = { id: string; studentNumber?: string; name?: string; nameKh?: string; photo?: string; sex?: string; user?: { name?: string } };
type Session = { session: number; scope: string; type: 'CHECK_IN' | 'CHECK_OUT'; startTime: string; endTime: string; classId?: string };
type RecordRow = { id: string; personId: string; status: string; session: number; scanMode?: string; checkInTime?: string };
type Mode = 'dashboard' | 'camera' | 'usb';

const STATUS = ['PRESENT', 'LATE', 'PERMISSION', 'ABSENT'];
const names = ['Morning Check-In', 'Morning Check-Out', 'Afternoon Check-In', 'Afternoon Check-Out'];
function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function pathOf(source: Source, params: Record<string, string>) { return source.path.replace(/:([a-zA-Z][a-zA-Z0-9_]*)/g, (_, key) => encodeURIComponent(params[key] || '')); }
function today() { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function displayName(student: Student) { return student.nameKh || student.name || student.user?.name || student.studentNumber || 'Student'; }
function timeLabel(value: string) { const [hour, minute] = value.slice(0, 5).split(':').map(Number); return new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(2000, 0, 1, hour, minute)); }

export default function PluginTakeAttendance({ pluginId, value, data, sources, options, loading, error }: any) {
  const classes = useMemo(() => rows<ClassRow>(value), [value]);
  const sessions = useMemo(() => rows<Session>(data[options.sessionsSource]).filter((item) => item.scope === 'STUDENT'), [data, options.sessionsSource]);
  const [classId, setClassId] = useState(''); const [sessionNumber, setSessionNumber] = useState(1); const [students, setStudents] = useState<Student[]>([]);
  const [records, setRecords] = useState<Record<string, RecordRow>>({}); const [statuses, setStatuses] = useState<Record<string, string>>({});
  const [mode, setMode] = useState<Mode>('dashboard'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [actionError, setActionError] = useState('');
  const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null); const [locationState, setLocationState] = useState('Finding location…');
  const [scanHistory, setScanHistory] = useState<RecordRow[]>([]); const [clock, setClock] = useState(new Date()); const [usbValue, setUsbValue] = useState('');
  const videoRef = useRef<HTMLVideoElement>(null); const readerRef = useRef<BrowserMultiFormatReader | null>(null); const scanLock = useRef(false); const usbInput = useRef<HTMLInputElement>(null);
  const getSource = useCallback((id: string) => sources.find((item: Source) => item.id === id) as Source | undefined, [sources]);
  const request = useCallback(async (sourceId: string, params: Record<string, string> = {}, body?: unknown, query?: Record<string, string>) => { const source = getSource(sourceId); if (!source) throw new Error('This action is unavailable.'); const search = query ? `?${new URLSearchParams(query)}` : ''; const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${pathOf(source, params)}${search}`, { method: source.method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(Array.isArray(result.message) ? result.message.join(' ') : result.message || `Request failed (${response.status})`); return result; }, [getSource, pluginId]);

  useEffect(() => { if (!classId && classes.length) { const requested = new URLSearchParams(window.location.search).get('classId'); setClassId(classes.some((item) => item.id === requested) ? requested! : classes[0].id); } }, [classId, classes]);
  useEffect(() => { const timer = window.setInterval(() => setClock(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!navigator.geolocation) { setLocationState('Location unavailable'); return; } navigator.geolocation.getCurrentPosition((position) => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setLocationState(`Location active (${position.coords.latitude.toFixed(4)}, ${position.coords.longitude.toFixed(4)})`); }, () => setLocationState('Location permission not granted'), { enableHighAccuracy: true, timeout: 10000 }); }, []);
  const applicableSessions = useMemo(() => { const exact = sessions.filter((item) => item.classId === classId); return exact.length ? exact : sessions.filter((item) => !item.classId); }, [sessions, classId]);
  useEffect(() => { if (!applicableSessions.length) return; const now = new Date(); const current = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`; const active = applicableSessions.find((item) => item.startTime.slice(0,5) <= current && item.endTime.slice(0,5) >= current); setSessionNumber(Number(active?.session || applicableSessions[0].session)); }, [applicableSessions]);
  const loadRoster = useCallback(async () => { if (!classId) return; setBusy(true); setActionError(''); try { const [studentResult, recordResult] = await Promise.all([request(options.studentsSource, { classId }), request(options.recordsSource, {}, undefined, { classId, date: today() })]); const nextStudents = rows<Student>(studentResult); const recordRows = rows<RecordRow>(recordResult).filter((item) => Number(item.session) === sessionNumber); const recordMap = Object.fromEntries(recordRows.map((item) => [item.personId, item])); setStudents(nextStudents); setRecords(recordMap); setStatuses(Object.fromEntries(nextStudents.map((item) => [item.id, recordMap[item.id]?.status || 'ABSENT']))); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Attendance roster could not be loaded.'); } finally { setBusy(false); } }, [classId, options.recordsSource, options.studentsSource, request, sessionNumber]);
  useEffect(() => { void loadRoster(); }, [loadRoster]);
  useEffect(() => () => { readerRef.current?.reset(); readerRef.current = null; }, []);

  const activeSession = applicableSessions.find((item) => Number(item.session) === sessionNumber);
  const summary = useMemo(() => students.reduce((result, student) => { const status = statuses[student.id] || 'ABSENT'; result[status] = (result[status] || 0) + 1; return result; }, {} as Record<string, number>), [students, statuses]);
  async function scan(code: string, scanMode: 'CAMERA' | 'USB') { if (!code.trim() || !classId || scanLock.current) return; scanLock.current = true; setActionError(''); try { const result = await request(options.scanSource, {}, { code: code.trim(), classId, session: sessionNumber, mode: scanMode, clientTimestamp: new Date().toISOString(), idempotencyKey: crypto.randomUUID(), ...location }); const record = result as RecordRow; setRecords((current) => ({ ...current, [record.personId]: record })); setStatuses((current) => ({ ...current, [record.personId]: record.status || 'PRESENT' })); setScanHistory((current) => [record, ...current.filter((item) => item.personId !== record.personId)].slice(0, 100)); setMessage(`${displayName(students.find((item) => item.id === record.personId) || { id: record.personId })} marked present.`); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Code could not be scanned.'); } finally { window.setTimeout(() => { scanLock.current = false; }, 900); } }
  async function submit() { setBusy(true); setActionError(''); setMessage(''); try { for (const student of students) await request(options.saveSource, {}, { personId: student.id, personType: 'STUDENT', classId, date: today(), session: sessionNumber, status: statuses[student.id] || 'ABSENT', ...location }); setMessage(`Attendance saved for ${students.length} students.`); await loadRoster(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Attendance could not be saved.'); } finally { setBusy(false); } }
  function openCamera() { setActionError(''); setMode('camera'); }
  useEffect(() => { if (mode !== 'camera') return; let cancelled = false; const start = async () => { if (!videoRef.current) return; try { const reader = new BrowserMultiFormatReader(); readerRef.current = reader; await reader.decodeFromVideoDevice(null, videoRef.current, (result) => { if (!cancelled && result) void scan(result.getText(), 'CAMERA'); }); } catch (cause) { if (!cancelled) setActionError(cause instanceof Error ? cause.message : 'Camera permission was not granted.'); } }; void start(); return () => { cancelled = true; readerRef.current?.reset(); readerRef.current = null; }; // The scanner is intentionally started only when the full-screen camera mounts.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);
  function closeMode() { readerRef.current?.reset(); readerRef.current = null; setMode('dashboard'); }
  function openUsb() { setMode('usb'); window.setTimeout(() => usbInput.current?.focus(), 50); }
  function sendUsb(event: React.FormEvent) { event.preventDefault(); const code = usbValue; setUsbValue(''); void scan(code, 'USB').finally(() => usbInput.current?.focus()); }

  return <section className="min-h-[65vh] space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-slate-900">Take Attendance</h1><p className="mt-1 text-sm text-slate-500"><span className="font-bold text-emerald-600">{summary.PRESENT || 0} present</span> · <span className="font-bold text-amber-600">{summary.LATE || 0} late</span> · {students.length} total · Session {sessionNumber} · {activeSession?.type === 'CHECK_OUT' ? '📤 Check-Out' : '📥 Check-In'}</p></div></header>
    {(message || actionError || error) && <div className={`rounded-xl border px-4 py-3 text-sm ${actionError || error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{actionError || error || message}</div>}
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><strong>🌙 Attendance Session</strong><span className="ml-2 text-indigo-600">{activeSession ? `${names[sessionNumber - 1]} · ${timeLabel(activeSession.startTime)} – ${timeLabel(activeSession.endTime)}` : 'No sessions configured'}</span></div><label className="mt-4 block max-w-sm text-xs font-semibold text-slate-600">Class<select value={classId} onChange={(event) => setClassId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{classes.map((item) => <option key={item.id} value={item.id}>{item.name}{item.subject ? ` — ${item.subject}` : ''}</option>)}</select></label><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{applicableSessions.map((item) => <button key={item.session} onClick={() => setSessionNumber(Number(item.session))} className={`rounded-xl border p-3 text-left text-xs ${Number(item.session) === sessionNumber ? 'border-blue-400 bg-blue-50 text-blue-700 ring-1 ring-blue-300' : 'border-slate-200 bg-slate-50 text-slate-500'}`}><strong className="block">{names[Number(item.session) - 1]}</strong>{timeLabel(item.startTime)} – {timeLabel(item.endTime)}</button>)}</div></div>
    <div className={`rounded-xl border px-4 py-3 text-sm ${location ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-amber-200 bg-amber-50 text-amber-700'}`}>📍 {locationState}</div>
    <div className="flex flex-wrap gap-3"><button disabled={!classId || !activeSession} onClick={() => void openCamera()} className="rounded-xl bg-teal-600 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">📷 Open Camera</button><button disabled={!classId || !activeSession} onClick={openUsb} className="rounded-xl bg-slate-800 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">🖱️ USB Scanner</button><button disabled={busy || !students.length} onClick={() => void submit()} className="rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">💾 {busy ? 'Saving…' : 'Submit'}</button></div>
    <div><div className="flex justify-between"><h2 className="text-xl font-bold text-slate-800">Student Roster</h2><span className="text-xs text-slate-400">{Object.keys(records).length}/{students.length} recorded</span></div>{loading || busy && !students.length ? <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-slate-100" />)}</div> : <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{students.map((student) => <article key={student.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3">{student.photo ? <img src={student.photo} alt="" className="h-11 w-11 rounded-full object-cover" /> : <span className="flex h-11 w-11 items-center justify-center rounded-full bg-slate-100 font-bold text-slate-500">{displayName(student)[0]}</span>}<div className="min-w-0 flex-1"><strong className="block truncate text-sm">{displayName(student)}</strong><span className="text-xs text-slate-400">{student.studentNumber || 'No student number'}</span></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statuses[student.id] === 'PRESENT' ? 'bg-emerald-100 text-emerald-700' : statuses[student.id] === 'LATE' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-600'}`}>{statuses[student.id] || 'ABSENT'}</span></div><select value={statuses[student.id] || 'ABSENT'} onChange={(event) => setStatuses({ ...statuses, [student.id]: event.target.value })} className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{STATUS.map((status) => <option key={status}>{status}</option>)}</select></article>)}</div>}{!loading && !students.length && <p className="mt-4 rounded-2xl border border-dashed p-10 text-center text-slate-400">No students are enrolled in this class.</p>}</div>
    {mode === 'camera' && <div className="fixed inset-0 z-[100] bg-black text-white"><video ref={videoRef} playsInline muted className="h-full w-full object-cover" /><div className="absolute inset-0 bg-black/35" /><div className="absolute left-6 top-6 rounded-full bg-sky-500 px-5 py-2 font-bold">{activeSession?.type === 'CHECK_OUT' ? '📤 Check-Out' : '📥 Check-In'} · Session {sessionNumber}</div><button onClick={closeMode} className="absolute right-7 top-6 flex h-14 w-14 items-center justify-center rounded-full bg-red-500 text-3xl">×</button><div className="pointer-events-none absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-3xl border-4 border-teal-300 shadow-[0_0_0_9999px_rgba(0,0,0,.15)]"><span className="absolute left-0 top-1/2 h-px w-full bg-teal-300" /></div><div className="absolute inset-x-6 bottom-24 rounded-2xl bg-emerald-500/90 p-4 text-center text-lg font-bold">Camera ready — scan student QR code</div><div className="absolute inset-x-6 bottom-5 flex items-center justify-between rounded-xl bg-black/60 p-3"><span>● Scanning for student QR codes…</span><span>{summary.PRESENT || 0} ✓ &nbsp; {summary.LATE || 0} ⚠ &nbsp; {students.length} total</span></div></div>}
    {mode === 'usb' && <div className="fixed inset-0 z-[100] flex flex-col bg-slate-950 text-white"><header className="flex items-center justify-between border-b border-slate-700 bg-slate-800 px-6 py-4"><button onClick={closeMode} className="font-bold">‹ Back</button><div className="flex-1 px-6"><h2 className="font-extrabold">🖱️ USB Scanner — Attendance</h2><p className="text-xs text-slate-400">School Attendance Management System</p></div><span className="rounded-full bg-slate-700 px-4 py-2 text-xs">S{sessionNumber} · {activeSession?.type?.replace('_', '-')}</span><strong className="ml-4 font-mono text-xl">{clock.toLocaleTimeString()}</strong></header><div className="flex flex-1 overflow-hidden"><main className="relative flex flex-1 flex-col items-center justify-center"><div className="absolute inset-x-0 top-0 bg-emerald-900/50 px-5 py-3 text-sm font-bold text-emerald-300">● Scanner active · {clock.toLocaleTimeString()}</div><div className="flex h-40 w-40 items-center justify-center rounded-[2.5rem] border border-emerald-500/30 bg-emerald-950 text-6xl shadow-[0_0_40px_rgba(16,185,129,.12)]">🖱️</div><h2 className="mt-7 text-4xl font-extrabold">Ready to Scan</h2><p className="mt-3 text-xl text-slate-400">Point scanner at a student QR card</p><form onSubmit={sendUsb} className="mt-8 w-full max-w-xl px-6"><input ref={usbInput} autoFocus value={usbValue} onChange={(event) => setUsbValue(event.target.value)} placeholder="Scanner input (press Enter)" className="w-full rounded-xl border border-slate-600 bg-slate-900 px-4 py-3 text-center font-mono outline-none focus:border-emerald-400" /></form>{actionError && <p className="mt-4 max-w-xl rounded-xl bg-red-950 px-4 py-3 text-red-300">{actionError}</p>}{message && !actionError && <p className="mt-4 max-w-xl rounded-xl bg-emerald-950 px-4 py-3 text-emerald-300">{message}</p>}</main><aside className="hidden w-80 border-l border-slate-700 bg-slate-800 p-5 md:block"><h3 className="font-bold">Attended Today</h3><div className="mt-5 space-y-2">{scanHistory.map((record) => { const student = students.find((item) => item.id === record.personId); return <div key={record.personId} className="rounded-xl bg-slate-700 p-3"><strong className="block text-sm">{student ? displayName(student) : record.personId}</strong><span className="text-xs text-emerald-300">✓ {new Date(record.checkInTime || Date.now()).toLocaleTimeString()}</span></div>; })}{!scanHistory.length && <p className="pt-32 text-center text-sm text-slate-500">📋<br />No scans yet</p>}</div></aside></div></div>}
  </section>;
}
