'use client';

type Field = { label: string; path: string };

function atPath(value: unknown, path: string): unknown { return path.split('.').reduce<unknown>((current, key) => current && typeof current === 'object' ? (current as Record<string, unknown>)[key] : undefined, value); }
function rows(value: unknown) { const candidate = Array.isArray(value) ? value : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : [value]; return candidate.filter((item: unknown) => item && typeof item === 'object') as Record<string, unknown>[]; }
function text(value: unknown) { return value === null || value === undefined ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value); }
function csvCell(value: unknown) { return `"${text(value).replace(/"/g, '""')}"`; }
function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export default function PluginPrintExport({ title, value, fields, options, loading, error }: { title?: string; value: unknown; fields: Field[]; options: { formats: Array<'print' | 'csv' | 'pdf'>; filename?: string; maximumRows?: number }; loading: boolean; error?: string }) {
  const limited = rows(value).slice(0, options.maximumRows || 10000); const filename = options.filename || 'plugin-export';
  function exportCsv() { const content = [fields.map((field) => csvCell(field.label)).join(','), ...limited.map((row) => fields.map((field) => csvCell(atPath(row, field.path))).join(','))].join('\r\n'); download(new Blob(['\uFEFF', content], { type: 'text/csv;charset=utf-8' }), `${filename}.csv`); }
  async function exportPdf() { const { default: jsPDF } = await import('jspdf'); const document = new jsPDF({ orientation: fields.length > 5 ? 'landscape' : 'portrait' }); document.setFontSize(16); document.text(title || 'Export', 14, 16); document.setFontSize(8); let y = 24; const lineHeight = 6; const widths = Math.max(25, (document.internal.pageSize.getWidth() - 28) / fields.length); const writeRow = (values: string[], heading = false) => { if (y > document.internal.pageSize.getHeight() - 12) { document.addPage(); y = 14; } if (heading) document.setFont('helvetica', 'bold'); values.forEach((entry, index) => document.text(entry.slice(0, 45), 14 + index * widths, y, { maxWidth: widths - 2 })); if (heading) document.setFont('helvetica', 'normal'); y += lineHeight; }; writeRow(fields.map((field) => field.label), true); limited.forEach((row) => writeRow(fields.map((field) => text(atPath(row, field.path))))); document.save(`${filename}.pdf`); }
  if (loading) return <section className="card p-6" aria-busy="true">Preparing export…</section>;
  if (error) return <section className="card border-red-200 p-6 text-red-700" role="alert">{error}</section>;
  return <section className="card overflow-hidden print:fixed print:inset-0 print:z-50 print:overflow-visible print:bg-white"><div className="flex items-center justify-between border-b border-slate-200 p-4 print:hidden"><h2 className="font-semibold text-slate-800">{title || 'Export'}</h2><div className="flex gap-2">{options.formats.includes('print') && <button className="btn btn-secondary" onClick={() => window.print()}>Print</button>}{options.formats.includes('csv') && <button className="btn btn-secondary" onClick={exportCsv}>CSV</button>}{options.formats.includes('pdf') && <button className="btn btn-primary" onClick={exportPdf}>PDF</button>}</div></div><div className="overflow-x-auto p-4"><h2 className="mb-4 hidden text-xl font-bold print:block">{title}</h2><table className="min-w-full border-collapse text-sm"><thead><tr>{fields.map((field) => <th key={field.path} className="border border-slate-300 bg-slate-50 px-3 py-2 text-left">{field.label}</th>)}</tr></thead><tbody>{limited.map((row, index) => <tr key={String(row.id ?? index)}>{fields.map((field) => <td key={field.path} className="border border-slate-300 px-3 py-2">{text(atPath(row, field.path)) || '—'}</td>)}</tr>)}</tbody></table>{!limited.length && <p className="py-8 text-center text-slate-500">No data to export.</p>}</div></section>;
}
