'use client';

import { useEffect, useRef, useState } from 'react';
import { BrowserMultiFormatReader } from '@zxing/library';
import { apiFetch } from '../../lib/api';
import { resolvePluginSourcePath } from '../../lib/plugin-ui-routing';

export default function PluginScanner({ pluginId, source, params, options, onSuccess }: any) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const readerRef = useRef<BrowserMultiFormatReader | null>(null); const lastRef = useRef({ value: '', at: 0 });
  const commandRef = useRef({ fingerprint: '', key: '' });
  const initialContext = Object.fromEntries((options.contextFields || []).map((field: any) => [field.id, field.defaultValue ?? '']));
  const [camera, setCamera] = useState(false); const [value, setValue] = useState(''); const [context, setContext] = useState<Record<string, string | number>>(initialContext); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => () => { readerRef.current?.reset(); readerRef.current = null; }, []);
  async function submit(code: string, mode: 'CAMERA' | 'USB') { const clean = code.trim(); if (clean.length < (options.minLength || 1) || clean.length > (options.maxLength || 1000)) return setMessage('Scanned value has an invalid length.'); for (const field of options.contextFields || []) if (field.required && (context[field.id] === '' || context[field.id] === undefined)) return setMessage(`${field.label} is required.`); const now = Date.now(); if (lastRef.current.value === clean && now - lastRef.current.at < (options.debounceMs || 1000)) return; lastRef.current = { value: clean, at: now }; const fingerprint = JSON.stringify([clean, mode, context]); if (commandRef.current.fingerprint !== fingerprint) commandRef.current = { fingerprint, key: globalThis.crypto.randomUUID() }; setBusy(true); setMessage(''); try { const endpoint = `/api/plugin-api/${encodeURIComponent(pluginId)}/${resolvePluginSourcePath(source.path, params)}`; const response = await apiFetch(endpoint, { method: source.method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [options.field]: clean, ...context, mode, clientTimestamp: new Date().toISOString(), idempotencyKey: commandRef.current.key }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || 'Scan rejected.'); setMessage(result.idempotentReplay ? 'Scan was already accepted.' : 'Scan accepted.'); setValue(''); commandRef.current = { fingerprint: '', key: '' }; await onSuccess(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Scan failed. Retry will safely reuse the same command.'); } finally { setBusy(false); } }
  async function startCamera() { if (!videoRef.current) return; setMessage(''); try { const reader = new BrowserMultiFormatReader(); readerRef.current = reader; setCamera(true); await reader.decodeFromVideoDevice(null, videoRef.current, (result) => { if (result) void submit(result.getText(), 'CAMERA'); }); } catch (cause) { setCamera(false); setMessage(cause instanceof Error ? cause.message : 'Camera is unavailable.'); } }
  function stopCamera() { readerRef.current?.reset(); readerRef.current = null; setCamera(false); }
  return <section className="card max-w-2xl p-5"><h2 className="font-semibold text-slate-800">Scanner</h2>{options.contextFields?.length > 0 && <div className="mt-4 grid gap-3 sm:grid-cols-2">{options.contextFields.map((field: any) => <label key={field.id} className="text-sm font-medium text-slate-700">{field.label}{field.required ? ' *' : ''}{field.type === 'select' ? <select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={context[field.id]} disabled={busy} onChange={(event) => setContext((current) => ({ ...current, [field.id]: event.target.value }))}><option value="">Select…</option>{field.options.map((option: any) => <option key={String(option.value)} value={option.value}>{option.label}</option>)}</select> : <input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" type={field.type === 'number' ? 'number' : 'text'} value={context[field.id]} disabled={busy} onChange={(event) => setContext((current) => ({ ...current, [field.id]: event.target.value }))} />}</label>)}</div>}{options.modes.includes('keyboard') && <form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); void submit(value, 'USB'); }}><label className="sr-only" htmlFor="plugin-scanner-code">Scan or enter code</label><input id="plugin-scanner-code" autoFocus className="flex-1 rounded-lg border border-slate-300 px-3 py-2 font-mono" value={value} disabled={busy} onChange={(event) => setValue(event.target.value)} placeholder="Scan or enter code, then press Enter" autoComplete="off" /><button className="btn btn-primary" disabled={busy}>Submit</button></form>}{options.modes.includes('camera') && <div className="mt-4"><video ref={videoRef} className={`aspect-video w-full rounded-lg bg-black ${camera ? '' : 'hidden'}`} muted playsInline /><button className="btn btn-secondary mt-2" disabled={busy} onClick={camera ? stopCamera : startCamera}>{camera ? 'Stop camera' : 'Start camera'}</button></div>}{message && <p className="mt-3 text-sm" role="status" aria-live="polite">{message}</p>}</section>;
}
