'use client';

import Link from 'next/link';
import { FormEvent, useMemo, useState } from 'react';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type Department = { id: string; name: string; nameKh?: string; description?: string };
type Officer = { id: string; userId: string; employeeNumber?: string; name?: string; email?: string; phone?: string; role?: string; position?: string; departmentId?: string; department?: Department; employmentStatus?: string; startedAt?: string; endedAt?: string; notes?: string; user?: { photo?: string } };

const positions = [
  ['TEACHER', 'Teacher'], ['PRIMARY_SCHOOL_PRINCIPAL', 'Primary School Principal'], ['SECONDARY_SCHOOL_PRINCIPAL', 'Secondary School Principal'],
  ['HIGH_SCHOOL_PRINCIPAL', 'High School Principal'], ['UNIVERSITY_RECTOR', 'University Rector'], ['OFFICER', 'Officer'], ['STAFF', 'Staff'],
  ['OFFICE_HEAD', 'Office Head'], ['DEPUTY_OFFICE_HEAD', 'Deputy Office Head'], ['DEPARTMENT_HEAD', 'Department Head'],
  ['DEPUTY_DEPARTMENT_HEAD', 'Deputy Department Head'], ['GENERAL_DEPARTMENT_DIRECTOR', 'General Department Director'],
  ['DEPUTY_GENERAL_DEPARTMENT_DIRECTOR', 'Deputy General Department Director'], ['COMPANY_CEO', 'Company CEO'], ['CREDIT_OFFICER', 'Credit Officer'],
  ['SECURITY_GUARD', 'Security Guard'], ['JANITOR', 'Janitor'], ['PROJECT_MANAGER', 'Project Manager'], ['BRANCH_MANAGER', 'Branch Manager'], ['EXECUTIVE_DIRECTOR', 'Executive Director'],
];
const emptyForm = { name: '', email: '', password: '', phone: '', photo: '', employeeNumber: '', position: 'OFFICER', departmentId: '', employmentStatus: 'ACTIVE', startedAt: new Date().toISOString().slice(0, 10), endedAt: '', notes: '' };
function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function labelPosition(code?: string) { return positions.find(([value]) => value === code)?.[1] || String(code || 'Officer').replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export default function PluginOfficerManager({ pluginId, value, data, sources, options, loading, error, onRefresh }: any) {
  const officers = useMemo(() => rows<Officer>(value), [value]); const departments = rows<Department>(data[options.departmentsSource]);
  const [tab, setTab] = useState<'officers' | 'departments'>('officers'); const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [department, setDepartment] = useState(''); const [position, setPosition] = useState('');
  const [form, setForm] = useState({ ...emptyForm }); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [formError, setFormError] = useState('');
  const [commandKey, setCommandKey] = useState('');
  const getSource = (id: string) => sources.find((item: Source) => item.id === id) as Source | undefined;
  async function request(sourceId: string, params: Record<string, string> = {}, body?: unknown) { const source = getSource(sourceId); if (!source) throw new Error('This action is unavailable.'); const path = source.path.replace(/:([a-zA-Z][a-zA-Z0-9_]*)/g, (_, key) => encodeURIComponent(params[key] || '')); const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${path}`, { method: source.method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(Array.isArray(result.message) ? result.message.join(' ') : result.message || `Request failed (${response.status})`); return result; }
  const shown = useMemo(() => officers.filter((item) => (!department || item.departmentId === department) && (!position || item.position === position) && `${item.name || ''} ${item.email || ''} ${item.phone || ''} ${item.employeeNumber || ''} ${item.position || ''}`.toLowerCase().includes(query.toLowerCase())), [officers, query, department, position]);
  const positionCounts = useMemo(() => new Map(officers.map((item) => item.position || item.role || 'OFFICER').map((key) => [key, officers.filter((item) => (item.position || item.role || 'OFFICER') === key).length])), [officers]);
  async function create(event: FormEvent) { event.preventDefault(); setFormError(''); if (!form.name.trim() || !form.email.trim() || form.password.length < 8) return setFormError('Name, email, and a password of at least 8 characters are required.'); const stableCommandKey = commandKey || `officer:${crypto.randomUUID()}`; setCommandKey(stableCommandKey); setBusy('create'); try { await request(options.createSource, {}, { ...form, commandKey: stableCommandKey, name: form.name.trim(), email: form.email.trim(), password: form.password, phone: form.phone.trim() || null, photo: form.photo.trim() || null, employeeNumber: form.employeeNumber.trim() || null, departmentId: form.departmentId || null, startedAt: form.startedAt || null, endedAt: form.endedAt || null, notes: form.notes.trim() || null }); setOpen(false); setForm({ ...emptyForm }); setCommandKey(''); setMessage('Login account, officer profile, and attendance ID card created successfully.'); await onRefresh(); } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'Officer could not be created.'); } finally { setBusy(''); } }
  async function deactivate(item: Officer) { if (!window.confirm(`Deactivate ${item.name || item.employeeNumber || 'this officer'}? Their login and attendance history will be preserved.`)) return; setBusy(`deactivate:${item.id}`); try { await request(options.deactivateSource, { officerId: item.id }, { employmentStatus: 'INACTIVE', endedAt: new Date().toISOString().slice(0, 10) }); setMessage('Officer deactivated.'); await onRefresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Officer could not be deactivated.'); } finally { setBusy(''); } }
  const input = 'mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100';
  return <div className="space-y-6">
    <header className="print:hidden"><h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Manage Officers</h1><p className="mt-1 text-slate-500">{officers.length} {officers.length === 1 ? 'Officer' : 'Officers'} · {departments.length} Departments</p><button onClick={() => window.print()} className="mt-2 rounded-xl border border-slate-300 bg-white px-5 py-2.5 font-semibold text-slate-700 hover:bg-slate-50">ID Cards</button></header>
    <div className="hidden print:grid print:grid-cols-2 print:gap-4">{officers.filter((item) => item.employmentStatus !== 'INACTIVE').map((item) => <article key={item.id} className="rounded-xl border-2 border-indigo-500 p-5"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-100 text-xl font-bold text-indigo-700">{(item.name || '?').slice(0, 2).toUpperCase()}</div><div><h2 className="text-lg font-bold">{item.name}</h2><p>{labelPosition(item.position)}</p><p className="text-sm">{item.department?.name || 'No Department'}</p></div></div><p className="mt-4 font-mono text-sm">ID: {item.employeeNumber || item.id.slice(0, 8)}</p></article>)}</div>
    <div className="flex gap-2 print:hidden"><button onClick={() => setTab('officers')} className={`rounded-2xl px-5 py-3 font-bold ${tab === 'officers' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-200' : 'border bg-white text-slate-700'}`}>Officers ({officers.length})</button><button onClick={() => setTab('departments')} className={`rounded-2xl px-5 py-3 font-bold ${tab === 'departments' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-200' : 'border bg-white text-slate-700'}`}>Departments ({departments.length})</button></div>
    {message && <div className="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-700 print:hidden">{message}</div>}
    {tab === 'departments' ? <section className="print:hidden"><div className="flex justify-end"><Link href={`/plugins/${pluginId}/${options.departmentsRoute}`} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Manage Departments</Link></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{departments.map((item) => { const count = officers.filter((officer) => officer.departmentId === item.id).length; return <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold text-slate-900">{item.name}</h2>{item.nameKh && <p className="text-sm text-indigo-600">{item.nameKh}</p>}</div><span className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-bold text-indigo-700">{count}</span></div>{item.description && <p className="mt-3 text-sm text-slate-500">{item.description}</p>}</article>; })}</div>{departments.length === 0 && <div className="rounded-2xl border border-dashed p-10 text-center text-slate-400">No departments yet</div>}</section> : <>
      <div className="flex justify-end print:hidden"><button onClick={() => { setOpen((current) => !current); setCommandKey(''); setFormError(''); }} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white shadow-lg shadow-indigo-200">{open ? '× Close' : '＋ Add Officer'}</button></div>
      {open && <form onSubmit={create} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm print:hidden"><h2 className="text-xl font-bold">New Officer</h2><p className="mt-1 text-sm text-slate-500">Create the secure login, officer profile, and scannable attendance ID in one workflow.</p>{formError && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{formError}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        <label className="text-sm font-semibold">Name *<input className={input} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Full name" required /></label><label className="text-sm font-semibold">Email *<input className={input} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="email@school.com" required /></label><label className="text-sm font-semibold">Temporary Password *<input className={input} type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} autoComplete="new-password" required /></label><label className="text-sm font-semibold">Phone<input className={input} value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="012 345 678" /></label><label className="text-sm font-semibold">Photo URL<input className={input} type="url" value={form.photo} onChange={(e) => setForm({ ...form, photo: e.target.value })} placeholder="https://…" /></label><label className="text-sm font-semibold">Employee Number<input className={input} value={form.employeeNumber} onChange={(e) => setForm({ ...form, employeeNumber: e.target.value })} placeholder="e.g. EMP-0001" /></label>
        <label className="text-sm font-semibold">Position *<select className={input} value={form.position} onChange={(e) => setForm({ ...form, position: e.target.value })}>{positions.map(([code, label]) => <option key={code} value={code}>{label} ({code})</option>)}</select></label>
        <label className="text-sm font-semibold">Department<select className={input} value={form.departmentId} onChange={(e) => setForm({ ...form, departmentId: e.target.value })}><option value="">— No Department —</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Employment Status<select className={input} value={form.employmentStatus} onChange={(e) => setForm({ ...form, employmentStatus: e.target.value })}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="SUSPENDED">Suspended</option></select></label>
        <label className="text-sm font-semibold">Start Date<input className={input} type="date" value={form.startedAt} onChange={(e) => setForm({ ...form, startedAt: e.target.value })} /></label><label className="text-sm font-semibold">End Date<input className={input} type="date" value={form.endedAt} onChange={(e) => setForm({ ...form, endedAt: e.target.value })} /></label><label className="text-sm font-semibold md:col-span-2">Notes<textarea className={input} rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label>
      </div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-5 py-3 font-semibold">Cancel</button><button disabled={busy === 'create'} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-60">{busy === 'create' ? 'Creating…' : 'Create Officer'}</button></div></form>}
      <div className="grid gap-3 lg:grid-cols-[320px_1fr] print:hidden"><input className={input} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search officers…" /><select className={input} value={department} onChange={(e) => setDepartment(e.target.value)}><option value="">All Departments</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
      <div className="flex flex-wrap gap-2 print:hidden"><button onClick={() => setPosition('')} className={`rounded-full px-4 py-2 text-sm ${!position ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'}`}>All ({officers.length})</button>{[...positionCounts].map(([code, count]) => <button key={code} onClick={() => setPosition(position === code ? '' : code)} className={`rounded-full px-4 py-2 text-sm ${position === code ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'}`}>{labelPosition(code)} ({count})</button>)}</div>
      {loading ? <div className="h-40 animate-pulse rounded-3xl bg-slate-100" /> : error ? <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div> : <div className="overflow-x-auto rounded-3xl border bg-white shadow-sm print:hidden"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Name','Email','Phone','Position','Departments','Status','Actions'].map((label) => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y">{shown.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-900">{item.name || 'Unknown user'}</p><p className="text-xs text-slate-400">{item.employeeNumber || 'No employee number'}</p></td><td className="px-5 py-4">{item.email || '—'}</td><td className="px-5 py-4">{item.phone || '—'}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1">{labelPosition(item.position)}</span></td><td className="px-5 py-4">{item.department?.name || '—'}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.employmentStatus === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700' : item.employmentStatus === 'SUSPENDED' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-500'}`}>{item.employmentStatus || 'ACTIVE'}</span></td><td className="whitespace-nowrap px-5 py-4"><button onClick={() => window.print()} title="Print ID card" className="mr-2 rounded-xl border px-3 py-2">▤</button><Link href={`/plugins/${pluginId}/${options.editRoute}/${item.id}`} title="Edit officer" className="mr-2 inline-block rounded-xl border px-3 py-2">✏️</Link>{item.employmentStatus !== 'INACTIVE' && <button disabled={Boolean(busy)} onClick={() => void deactivate(item)} title="Deactivate officer" className="rounded-xl border px-3 py-2 text-slate-500">♙</button>}</td></tr>)}</tbody></table>{shown.length === 0 && <p className="p-10 text-center text-slate-400">No officers match these filters.</p>}</div>}
    </>}
  </div>;
}
