'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function isoToday() { const date=new Date(); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
const statusColors: Record<string,string> = { PRESENT: '#10b981', ABSENT: '#ef4444', LATE: '#f59e0b', PERMISSION: '#3b82f6' };

export default function PluginAttendanceDashboard({ pluginId, value, data, options, loading, error, onRefresh }: any) {
  const classes=useMemo(()=>rows<any>(value),[value]); const officers=rows<any>(data[options.officersSource]); const authoritative:any=data[options.authoritativeSource]||{};
  const [query,setQuery]=useState(''); const rosterTotal=rows<any>(authoritative.classProgress).reduce((sum,item)=>sum+Number(item.students||0),0); const totalStudents=rosterTotal||classes.reduce((sum,item)=>sum+Number(item.studentCount||0),0); const activeStaff=officers.filter((item)=>item.employmentStatus==='ACTIVE').length;
  const student=authoritative.student||{present:0,late:0,permission:0,absent:0,expected:0}; const staff=authoritative.staff||{present:0,late:0,permission:0,absent:0,expected:0};
  const attendance=Math.round(((student.present+student.late+staff.present+staff.late)/Math.max(student.expected+staff.expected,1))*100); const date=new Date();
  const quick=[['▣','Take Attendance','attendance'],['✎','Add Attendance','attendance'],['📊','Reports','reports'],['👥','Staff Reports','staff-attendance-reports'],['🎓','Classes','classes'],['🎉','Holidays','settings'],['⏰','Sessions','settings'],['🧹','Identification','student-id-cards']];
  const searched=rows<any>(authoritative.classProgress).filter((item)=>String(item.className||'').toLowerCase().includes(query.toLowerCase()));
  function summary(title:string,values:any,total:number){return <section className="rounded-2xl border bg-white p-4 shadow-sm"><h2 className="mb-3 text-sm font-extrabold uppercase text-slate-700">▌ {title}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['PRESENT',values.present],['ABSENT',values.absent],['LATE',values.late],['PERMISSION',values.permission]].map(([label,count])=><div key={String(label)} className="rounded-xl border p-4" style={{backgroundColor:`${statusColors[String(label)]}0d`,borderColor:`${statusColors[String(label)]}55`}}><span className="text-xs font-bold" style={{color:statusColors[String(label)]}}>◉ {label}</span><strong className="mt-2 block text-2xl">{count}</strong><span className="text-[10px] text-slate-400">of {total} total</span></div>)}</div></section>}
  function donut(title:string,values:any){const total=Math.max(values.present+values.absent+values.late+values.permission,1);const a=values.present/total*360,b=a+values.absent/total*360,c=b+values.late/total*360;return <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="text-sm font-bold">▌ {title}</h3><div className="mx-auto mt-5 h-32 w-32 rounded-full" style={{background:`conic-gradient(${statusColors.PRESENT} 0 ${a}deg,${statusColors.ABSENT} ${a}deg ${b}deg,${statusColors.LATE} ${b}deg ${c}deg,${statusColors.PERMISSION} ${c}deg 360deg)`}}><div className="relative left-8 top-8 h-16 w-16 rounded-full bg-white"/></div><p className="mt-4 text-center text-xs text-slate-500">● Present &nbsp; ● Absent &nbsp; ● Late &nbsp; ● Permission</p></div>}
  return <section className="space-y-5 bg-slate-50 p-1 sm:p-4"><header className="rounded-2xl bg-gradient-to-r from-slate-950 via-indigo-950 to-indigo-700 p-6 text-white shadow-lg"><div className="flex flex-wrap justify-between gap-4"><div><span className="text-[10px] uppercase tracking-widest text-indigo-200">Academic Attendance · Admin</span><h1 className="mt-1 text-2xl font-extrabold">{date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</h1><p className="mt-1 text-xs text-indigo-200">{date.toLocaleTimeString()} · Cambodia Time <button onClick={()=>void onRefresh()} className="ml-3 rounded bg-white/15 px-2 py-1">↻ Refresh</button></p></div><div className="flex items-center gap-5"><div className="flex h-20 w-20 items-center justify-center rounded-full border-4 border-indigo-300 text-xl font-bold">{attendance}%</div><div className="grid grid-cols-2 gap-x-5 gap-y-2 text-xs"><span>Total<br/><b className="text-lg">{totalStudents+activeStaff}</b></span><span>Present<br/><b className="text-lg">{student.present+staff.present}</b></span><span>Absent<br/><b className="text-lg">{student.absent+staff.absent}</b></span><span>Late<br/><b className="text-lg">{student.late+staff.late}</b></span></div></div></div></header>
    {error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
    {authoritative.date&&<div className={`rounded-xl border px-4 py-3 text-sm ${authoritative.holiday?'border-amber-300 bg-amber-50 text-amber-800':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{authoritative.holiday?'🎉 Today is configured as a school holiday. Attendance is not expected.':`● Live attendance for ${authoritative.date} · recorded scans appear immediately.`}</div>}
    <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><h2 className="text-sm font-bold">QUICK ACTIONS</h2><span className="text-xs text-slate-400">Shortcuts to common tasks</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-8">{quick.map(([icon,label,route])=><Link key={label} href={`/plugins/${pluginId}/${route}`} className="rounded-xl border p-3 text-center hover:border-indigo-400 hover:bg-indigo-50"><span className="text-xl">{icon}</span><strong className="mt-2 block text-xs">{label}</strong></Link>)}</div></section>
    <div className="grid gap-3 md:grid-cols-4">{[['🟢','PERFECT CLASSES',classes.filter((item)=>Number(item.studentCount||0)>0&&student.absent===0).length,'No absences'],['⭐','PERFECT ATTENDANCE',student.present+staff.present,'Present today'],['🟡','PERMISSION',student.permission+staff.permission,'On permitted leave'],['🔴','MOST ATTENTION',student.absent+staff.absent,'Absent today']].map(([icon,label,count,detail],index)=><div key={String(label)} className={`rounded-xl border p-4 ${index===0?'border-emerald-200 bg-emerald-50':index===1?'border-blue-200 bg-blue-50':index===2?'border-amber-200 bg-amber-50':'border-red-200 bg-red-50'}`}><span className="text-[10px] font-bold">{icon} {label}</span><strong className="mt-2 block text-xl">{count}</strong><span className="text-[10px] text-slate-500">{detail}</span></div>)}</div>
    {summary('Students Attendance Summary',student,totalStudents)}<section className="rounded-2xl border bg-white p-4 shadow-sm"><h2 className="text-sm font-bold">▌ Student Status</h2><div className="mt-3 rounded-xl border border-indigo-200 bg-indigo-50 p-4"><span className="text-xs font-bold text-indigo-700">TOTAL STUDENTS · STUDY YEAR</span><strong className="mt-1 block text-2xl">{totalStudents}</strong><span className="float-right text-xs text-emerald-600">Active {totalStudents-student.absent} &nbsp; Without class 0</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-red-200 bg-red-50 p-4"><span className="text-xs font-bold text-red-600">NO ENROLLMENT</span><strong className="block text-xl">0</strong></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><span className="text-xs font-bold text-amber-600">INCOMPLETE ENROLLMENT</span><strong className="block text-xl">0</strong></div></div></section>{summary('Staff Attendance Summary',staff,activeStaff)}
    <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-sm font-bold">▌ Class Attendance Progress <span className="rounded-full bg-emerald-100 px-2 text-[10px] text-emerald-700">Live authoritative</span></h2><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search class…" className="rounded-lg border px-3 py-2 text-xs"/></div><div className="mt-4 grid grid-cols-6 border-b pb-2 text-[10px] font-bold uppercase text-slate-400"><span>Class</span><span>Students</span><span>Expected</span><span>Present</span><span>Absent</span><span>Rate</span></div>{searched.map((item)=><div key={item.classId} className="py-3"><div className="grid grid-cols-6 text-xs"><b>{item.className}</b><span>{item.students}</span><span>{item.expected}</span><span className="text-emerald-600">{item.present+item.late}</span><span className="text-red-500">{item.absent}</span><b>{item.rate}%</b></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full rounded bg-gradient-to-r from-emerald-400 to-indigo-500" style={{width:`${item.rate}%`}}/></div></div>)}{!loading&&!searched.length&&<p className="p-6 text-center text-slate-400">No elapsed or recorded class sessions for today.</p>}{loading&&<p className="p-6 text-center text-slate-400">Loading dashboard…</p>}</section>
    <div className="grid gap-4 lg:grid-cols-2">{donut('Students Attendance Summary · Attendance Distribution',student)}{donut('Staff Attendance Summary · Attendance Distribution',staff)}</div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="text-sm font-bold">▌ Monthly Attendance Trend</h2><span className="text-xs text-slate-400">{date.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</span></div><div className="mt-6 flex h-32 items-end gap-1 border-b border-l pl-2">{Array.from({length:new Date(date.getFullYear(),date.getMonth()+1,0).getDate()},(_,index)=><div key={index} className="flex-1 bg-gradient-to-t from-cyan-400 to-indigo-500" style={{height:`${Math.max(2,index+1===date.getDate()?attendance:2)}%`}} title={`Day ${index+1}`}/>)}</div></section>
  </section>;
}
