'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { BrowserMultiFormatReader } from '@zxing/library';
import { apiFetch } from '../../lib/api';

type Source = { id: string; method: string; path: string };
type ClassRow = { id: string; name: string; subject?: string; schedule?: string };
type Student = { id: string; studentNumber?: string; name?: string; nameKh?: string; photo?: string; sex?: string; user?: { name?: string } };
type Session = { session: number; scope: string; type: 'CHECK_IN' | 'CHECK_OUT'; startTime: string; endTime: string; classId?: string };
type RecordRow = { id: string; personId: string; status: string; session: number; scanMode?: string; checkInTime?: string };
type Mode = 'dashboard' | 'camera' | 'usb';

const STATUS = ['PRESENT', 'LATE', 'PERMISSION', 'ABSENT'];
const names = ['Morning Check-In', 'Morning Check-Out', 'Afternoon Check-In', 'Afternoon Check-Out'];
function rows<T>(value: unknown): T[] { return Array.isArray(value) ? value as T[] : value && typeof value === 'object' && Array.isArray((value as any).items) ? (value as any).items : []; }
function pathOf(source: Source, params: Record<string, string>) { return source.path.replace(/:([a-zA-Z][a-zA-Z0-9_]*)/g, (_, key) => encodeURIComponent(params[key] || '')); }
function today() { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function displayName(student: Student) { return student.nameKh || student.name || student.user?.name || student.studentNumber || 'Student'; }
function timeLabel(value: string) { const [hour, minute] = value.slice(0, 5).split(':').map(Number); return new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(2000, 0, 1, hour, minute)); }
function timeWithinWindow(current: string, start: string, end: string) { const from = start.slice(0, 5); const until = end.slice(0, 5); return from <= until ? current >= from && current <= until : current >= from || current <= until; }
function physicalKeyToAscii(event: KeyboardEvent) {
  const { code, shiftKey } = event;
  if (code.startsWith('Key')) { const letter = code.slice(3); return shiftKey ? letter : letter.toLowerCase(); }
  if (code.startsWith('Digit')) { const digit = code.slice(5); if (!shiftKey) return digit; return ({ '1': '!', '2': '@', '3': '#', '4': '$', '5': '%', '6': '^', '7': '&', '8': '*', '9': '(', '0': ')' } as Record<string, string>)[digit] || digit; }
  if (code.startsWith('Numpad') && /^\d$/.test(code.slice(6))) return code.slice(6);
  const punctuation: Record<string, [string, string]> = { Minus: ['-', '_'], Equal: ['=', '+'], BracketLeft: ['[', '{'], BracketRight: [']', '}'], Backslash: ['\\', '|'], Semicolon: [';', ':'], Quote: ["'", '"'], Backquote: ['`', '~'], Comma: [',', '<'], Period: ['.', '>'], Slash: ['/', '?'], Space: [' ', ' '] };
  if (punctuation[code]) return punctuation[code][shiftKey ? 1 : 0];
  return event.key?.length === 1 && event.key.charCodeAt(0) >= 32 ? event.key : null;
}

export default function PluginTakeAttendance({ pluginId, value, data, sources, options, loading, error }: any) {
  const classes = useMemo(() => rows<ClassRow>(value), [value]);
  const sessions = useMemo(() => rows<Session>(data[options.sessionsSource]).filter((item) => item.scope === 'STUDENT'), [data, options.sessionsSource]);
  const [classId, setClassId] = useState(''); const [sessionNumber, setSessionNumber] = useState(1); const [students, setStudents] = useState<Student[]>([]);
  const [records, setRecords] = useState<Record<string, RecordRow>>({}); const [statuses, setStatuses] = useState<Record<string, string>>({});
  const [mode, setMode] = useState<Mode>('dashboard'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [actionError, setActionError] = useState('');
  const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null); const [locationState, setLocationState] = useState('Finding location…');
  const [scanHistory, setScanHistory] = useState<RecordRow[]>([]); const [clock, setClock] = useState(new Date()); const [usbValue, setUsbValue] = useState('');
  const [usbActive, setUsbActive] = useState(false); const [usbLastActivity, setUsbLastActivity] = useState<Date | null>(null); const [usbTestMode, setUsbTestMode] = useState(false); const [usbTestResult, setUsbTestResult] = useState('');
  const [hidSupported, setHidSupported] = useState(false); const [hidDeviceName, setHidDeviceName] = useState('');
  const videoRef = useRef<HTMLVideoElement>(null); const readerRef = useRef<BrowserMultiFormatReader | null>(null); const scanLock = useRef(false); const lastScan = useRef({ code: '', at: 0 }); const usbInput = useRef<HTMLInputElement>(null);
  const usbBuffer = useRef(''); const usbLastKey = useRef(0); const usbActivityTimer = useRef<number | null>(null); const scanRef = useRef<(code: string, mode: 'CAMERA' | 'USB') => Promise<void>>(async () => {});
  const getSource = useCallback((id: string) => sources.find((item: Source) => item.id === id) as Source | undefined, [sources]);
  const request = useCallback(async (sourceId: string, params: Record<string, string> = {}, body?: unknown, query?: Record<string, string>) => { const source = getSource(sourceId); if (!source) throw new Error('This action is unavailable.'); const search = query ? `?${new URLSearchParams(query)}` : ''; const response = await apiFetch(`/api/plugin-api/${encodeURIComponent(pluginId)}/${pathOf(source, params)}${search}`, { method: source.method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(Array.isArray(result.message) ? result.message.join(' ') : result.message || `Request failed (${response.status})`); return result; }, [getSource, pluginId]);

  useEffect(() => { if (!classId && classes.length) { const requested = new URLSearchParams(window.location.search).get('classId'); setClassId(classes.some((item) => item.id === requested) ? requested! : classes[0].id); } }, [classId, classes]);
  useEffect(() => { const timer = window.setInterval(() => setClock(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!navigator.geolocation) { setLocationState('Location unavailable'); return; } navigator.geolocation.getCurrentPosition((position) => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setLocationState(`Location active (${position.coords.latitude.toFixed(4)}, ${position.coords.longitude.toFixed(4)})`); }, () => setLocationState('Location permission not granted'), { enableHighAccuracy: true, timeout: 10000 }); }, []);
  const applicableSessions = useMemo(() => { const exact = sessions.filter((item) => item.classId === classId); return exact.length ? exact : sessions.filter((item) => !item.classId); }, [sessions, classId]);
  useEffect(() => { if (!applicableSessions.length) return; const current = `${String(clock.getHours()).padStart(2, '0')}:${String(clock.getMinutes()).padStart(2, '0')}`; const active = applicableSessions.find((item) => timeWithinWindow(current, item.startTime, item.endTime)); if (active) setSessionNumber(Number(active.session)); }, [applicableSessions, clock]);
  const loadRoster = useCallback(async () => { if (!classId) return; setBusy(true); setActionError(''); try { const [studentResult, recordResult] = await Promise.all([request(options.studentsSource, { classId }), request(options.recordsSource, {}, undefined, { classId, date: today() })]); const nextStudents = rows<Student>(studentResult); const recordRows = rows<RecordRow>(recordResult).filter((item) => Number(item.session) === sessionNumber); const recordMap = Object.fromEntries(recordRows.map((item) => [item.personId, item])); setStudents(nextStudents); setRecords(recordMap); setStatuses(Object.fromEntries(nextStudents.map((item) => [item.id, recordMap[item.id]?.status || 'ABSENT']))); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Attendance roster could not be loaded.'); } finally { setBusy(false); } }, [classId, options.recordsSource, options.studentsSource, request, sessionNumber]);
  useEffect(() => { void loadRoster(); }, [loadRoster]);
  useEffect(() => () => { readerRef.current?.reset(); readerRef.current = null; }, []);

  const activeSession = applicableSessions.find((item) => Number(item.session) === sessionNumber);
  const currentTime = `${String(clock.getHours()).padStart(2, '0')}:${String(clock.getMinutes()).padStart(2, '0')}`;
  const activeSessionIsOpen = Boolean(activeSession && timeWithinWindow(currentTime, activeSession.startTime, activeSession.endTime));
  const summary = useMemo(() => students.reduce((result, student) => { const status = statuses[student.id] || 'ABSENT'; result[status] = (result[status] || 0) + 1; return result; }, {} as Record<string, number>), [students, statuses]);
  async function scan(code: string, scanMode: 'CAMERA' | 'USB') { const clean = code.trim(); const detectedAt = Date.now(); if (!clean || !classId || scanLock.current) return; if (lastScan.current.code === clean && detectedAt - lastScan.current.at < 3000) return; lastScan.current = { code: clean, at: detectedAt }; scanLock.current = true; setActionError(''); setMessage('QR detected — recording attendance…'); try { const result = await request(options.scanSource, {}, { code: clean, classId, session: sessionNumber, mode: scanMode, clientTimestamp: new Date().toISOString(), idempotencyKey: crypto.randomUUID(), ...location }); const record = result as RecordRow; setRecords((current) => ({ ...current, [record.personId]: record })); setStatuses((current) => ({ ...current, [record.personId]: record.status || 'PRESENT' })); setScanHistory((current) => [record, ...current.filter((item) => item.personId !== record.personId)].slice(0, 100)); setMessage(`${displayName(students.find((item) => item.id === record.personId) || { id: record.personId })} marked present.`); navigator.vibrate?.(100); } catch (cause) { setMessage(''); setActionError(cause instanceof Error ? cause.message : 'Code could not be scanned.'); navigator.vibrate?.([80, 60, 80]); } finally { window.setTimeout(() => { scanLock.current = false; }, 900); } }
  scanRef.current = scan;
  async function submit() { setBusy(true); setActionError(''); setMessage(''); try { for (const student of students) await request(options.saveSource, {}, { personId: student.id, personType: 'STUDENT', classId, date: today(), session: sessionNumber, status: statuses[student.id] || 'ABSENT', ...location }); setMessage(`Attendance saved for ${students.length} students.`); await loadRoster(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Attendance could not be saved.'); } finally { setBusy(false); } }
  function openCamera() { setActionError(''); setMode('camera'); }
  useEffect(() => { if (mode !== 'camera') return; let cancelled = false; const start = async () => { if (!videoRef.current) return; try { const reader = new BrowserMultiFormatReader(); readerRef.current = reader; await reader.decodeFromVideoDevice(null, videoRef.current, (result) => { if (!cancelled && result) void scan(result.getText(), 'CAMERA'); }); } catch (cause) { if (!cancelled) setActionError(cause instanceof Error ? cause.message : 'Camera permission was not granted.'); } }; void start(); return () => { cancelled = true; readerRef.current?.reset(); readerRef.current = null; }; // The scanner is intentionally started only when the full-screen camera mounts.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);
  function closeMode() { readerRef.current?.reset(); readerRef.current = null; setMode('dashboard'); }
  function openUsb() { setActionError(''); setMessage(''); setUsbTestResult(''); setMode('usb'); window.setTimeout(() => usbInput.current?.focus(), 50); }
  function sendUsb(event: React.FormEvent) { event.preventDefault(); const code = usbValue; setUsbValue(''); void scan(code, 'USB').finally(() => usbInput.current?.focus()); }
  useEffect(() => {
    setHidSupported(typeof navigator !== 'undefined' && 'hid' in navigator);
    if (!('hid' in navigator)) return;
    const hid = (navigator as any).hid;
    const refresh = () => hid.getDevices().then((devices: any[]) => setHidDeviceName(devices[0]?.productName || '')).catch(() => {});
    refresh(); hid.addEventListener('connect', refresh); hid.addEventListener('disconnect', refresh);
    return () => { hid.removeEventListener('connect', refresh); hid.removeEventListener('disconnect', refresh); };
  }, []);
  async function detectUsb() { if (!hidSupported) { setMessage('This browser uses keyboard-mode detection. Scan a card to verify the device.'); return; } try { const devices = await (navigator as any).hid.requestDevice({ filters: [] }); if (devices[0]) { setHidDeviceName(devices[0].productName || 'USB HID scanner'); setMessage(`${devices[0].productName || 'USB scanner'} connected.`); } } catch { /* Device chooser cancelled. */ } }
  useEffect(() => {
    if (mode !== 'usb') return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.ctrlKey || event.altKey || event.metaKey) return;
      const now = Date.now(); if (now - usbLastKey.current > 250) usbBuffer.current = '';
      usbLastKey.current = now; setUsbActive(true); setUsbLastActivity(new Date());
      if (usbActivityTimer.current) window.clearTimeout(usbActivityTimer.current);
      usbActivityTimer.current = window.setTimeout(() => setUsbActive(false), 2500);
      if (event.key === 'Enter' || event.code === 'NumpadEnter') {
        event.preventDefault(); const code = usbBuffer.current.trim(); usbBuffer.current = ''; setUsbValue('');
        if (!code) return;
        if (usbTestMode) { setUsbTestResult(code); setMessage('Scanner test passed — code received. Turn off Test to record attendance.'); navigator.vibrate?.(80); }
        else void scanRef.current(code, 'USB');
        return;
      }
      if (event.key === 'Backspace') { event.preventDefault(); usbBuffer.current = usbBuffer.current.slice(0, -1); setUsbValue(usbBuffer.current); return; }
      const character = physicalKeyToAscii(event); if (character === null) return;
      event.preventDefault(); usbBuffer.current += character; setUsbValue(usbBuffer.current);
    };
    window.addEventListener('keydown', onKeyDown, true);
    return () => { window.removeEventListener('keydown', onKeyDown, true); if (usbActivityTimer.current) window.clearTimeout(usbActivityTimer.current); };
  }, [mode, usbTestMode]);

  return <section className="min-h-[65vh] space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-slate-900">Take Attendance</h1><p className="mt-1 text-sm text-slate-500"><span className="font-bold text-emerald-600">{summary.PRESENT || 0} present</span> · <span className="font-bold text-amber-600">{summary.LATE || 0} late</span> · {students.length} total · Session {sessionNumber} · {activeSession?.type === 'CHECK_OUT' ? '📤 Check-Out' : '📥 Check-In'}</p></div></header>
    {(message || actionError || error) && <div className={`rounded-xl border px-4 py-3 text-sm ${actionError || error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{actionError || error || message}</div>}
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><strong>🌙 Attendance Session</strong><span className="ml-2 text-indigo-600">{activeSession ? `${names[sessionNumber - 1]} · ${timeLabel(activeSession.startTime)} – ${timeLabel(activeSession.endTime)}` : 'No sessions configured'}</span></div><label className="mt-4 block max-w-sm text-xs font-semibold text-slate-600">Class<select value={classId} onChange={(event) => setClassId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{classes.map((item) => <option key={item.id} value={item.id}>{item.name}{item.subject ? ` — ${item.subject}` : ''}</option>)}</select></label><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{applicableSessions.map((item) => <button key={item.session} onClick={() => setSessionNumber(Number(item.session))} className={`rounded-xl border p-3 text-left text-xs ${Number(item.session) === sessionNumber ? 'border-blue-400 bg-blue-50 text-blue-700 ring-1 ring-blue-300' : 'border-slate-200 bg-slate-50 text-slate-500'}`}><strong className="block">{names[Number(item.session) - 1]}</strong>{timeLabel(item.startTime)} – {timeLabel(item.endTime)}</button>)}</div></div>
    <div className={`rounded-xl border px-4 py-3 text-sm ${location ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-amber-200 bg-amber-50 text-amber-700'}`}>📍 {locationState}</div>
    {!activeSessionIsOpen && activeSession && <div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-800">No attendance session is active now. Session {sessionNumber} accepts scans from {timeLabel(activeSession.startTime)} to {timeLabel(activeSession.endTime)}.</div>}
    <div className="flex flex-wrap gap-3"><button disabled={!classId || !activeSessionIsOpen} onClick={() => void openCamera()} className="rounded-xl bg-teal-600 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">📷 Open Camera</button><button disabled={!classId || !activeSessionIsOpen} onClick={openUsb} className="rounded-xl bg-slate-800 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">🖱️ USB Scanner</button><button disabled={busy || !students.length} onClick={() => void submit()} className="rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white shadow-lg disabled:opacity-50">💾 {busy ? 'Saving…' : 'Submit'}</button></div>
    <div><div className="flex justify-between"><h2 className="text-xl font-bold text-slate-800">Student Roster</h2><span className="text-xs text-slate-400">{Object.keys(records).length}/{students.length} recorded</span></div>{loading || busy && !students.length ? <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-28 animate-pulse rounded-2xl bg-slate-100" />)}</div> : <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{students.map((student) => <article key={student.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3">{student.photo ? <img src={student.photo} alt="" className="h-11 w-11 rounded-full object-cover" /> : <span className="flex h-11 w-11 items-center justify-center rounded-full bg-slate-100 font-bold text-slate-500">{displayName(student)[0]}</span>}<div className="min-w-0 flex-1"><strong className="block truncate text-sm">{displayName(student)}</strong><span className="text-xs text-slate-400">{student.studentNumber || 'No student number'}</span></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statuses[student.id] === 'PRESENT' ? 'bg-emerald-100 text-emerald-700' : statuses[student.id] === 'LATE' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-600'}`}>{statuses[student.id] || 'ABSENT'}</span></div><select value={statuses[student.id] || 'ABSENT'} onChange={(event) => setStatuses({ ...statuses, [student.id]: event.target.value })} className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{STATUS.map((status) => <option key={status}>{status}</option>)}</select></article>)}</div>}{!loading && !students.length && <p className="mt-4 rounded-2xl border border-dashed p-10 text-center text-slate-400">No students are enrolled in this class.</p>}</div>
    {mode === 'camera' && <div className="fixed inset-0 z-[100] bg-black text-white"><video ref={videoRef} playsInline muted className="h-full w-full object-cover" /><div className="absolute inset-0 bg-black/35" /><div className="absolute left-6 top-6 rounded-full bg-sky-500 px-5 py-2 font-bold">{activeSession?.type === 'CHECK_OUT' ? '📤 Check-Out' : '📥 Check-In'} · Session {sessionNumber}</div><button onClick={closeMode} className="absolute right-7 top-6 flex h-14 w-14 items-center justify-center rounded-full bg-red-500 text-3xl">×</button><div className="pointer-events-none absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-3xl border-4 border-teal-300 shadow-[0_0_0_9999px_rgba(0,0,0,.15)]"><span className="absolute left-0 top-1/2 h-px w-full bg-teal-300" /></div><div className={`absolute inset-x-6 bottom-24 rounded-2xl p-4 text-center text-lg font-bold ${actionError ? 'bg-red-600/95' : message ? 'bg-emerald-600/95' : 'bg-slate-900/80'}`} role="status" aria-live="assertive">{actionError || message || 'Camera ready — scan student QR code'}</div><div className="absolute inset-x-6 bottom-5 flex items-center justify-between rounded-xl bg-black/60 p-3"><span>● Scanning for student QR codes…</span><span>{summary.PRESENT || 0} ✓ &nbsp; {summary.LATE || 0} ⚠ &nbsp; {students.length} total</span></div></div>}
    {mode === 'usb' && <div className="fixed inset-0 z-[100] flex flex-col bg-slate-950 text-white">
      <header className="flex items-center gap-4 border-b border-slate-700 bg-slate-800 px-4 py-3 sm:px-6"><button onClick={closeMode} className="rounded-lg px-3 py-2 font-bold hover:bg-slate-700">‹ Back</button><div className="min-w-0 flex-1"><h2 className="truncate font-extrabold">🖱️ USB Scanner — Attendance</h2><p className="text-xs text-slate-400">{classes.find((item) => item.id === classId)?.name || 'School Attendance Management System'}</p></div><span className="hidden rounded-full bg-slate-700 px-4 py-2 text-xs sm:block">S{sessionNumber} · {activeSession?.type?.replace('_', '-')}</span><strong className="font-mono text-sm sm:text-xl">{clock.toLocaleTimeString()}</strong></header>
      <div className="flex items-center gap-3 border-b border-emerald-700/40 bg-emerald-950/70 px-5 py-2.5 text-sm"><span className={`h-3 w-3 rounded-full ${usbActive ? 'animate-pulse bg-emerald-400' : 'bg-slate-500'}`} /><strong className={usbActive ? 'text-emerald-300' : 'text-slate-300'}>{usbActive ? 'Scanner input detected' : hidDeviceName ? `${hidDeviceName} ready` : 'Waiting for USB scanner…'}</strong><span className="ml-auto hidden text-xs text-slate-400 sm:block">{usbLastActivity ? `Last activity ${usbLastActivity.toLocaleTimeString()}` : 'Scan a card to verify'}</span><button onClick={() => void detectUsb()} className="rounded-lg bg-slate-700 px-3 py-1.5 font-bold hover:bg-slate-600">Detect</button><button onClick={() => { setUsbTestMode((current) => !current); setUsbTestResult(''); setMessage(''); }} className={`rounded-lg px-3 py-1.5 font-bold ${usbTestMode ? 'bg-amber-500 text-slate-950' : 'bg-slate-700 hover:bg-slate-600'}`}>{usbTestMode ? 'Testing' : 'Test'}</button></div>
      <div className="flex min-h-0 flex-1 overflow-hidden"><main className="relative flex min-w-0 flex-1 flex-col items-center justify-center p-6"><div className={`flex h-36 w-36 items-center justify-center rounded-[2.5rem] border text-6xl shadow-[0_0_40px_rgba(16,185,129,.12)] ${usbActive ? 'border-emerald-400 bg-emerald-900 ring-4 ring-emerald-500/20' : 'border-emerald-500/30 bg-emerald-950'}`}>🖱️</div><h2 className="mt-6 text-center text-3xl font-extrabold sm:text-4xl">{usbTestMode ? 'Scanner Test Mode' : 'Ready to Scan'}</h2><p className="mt-3 text-center text-base text-slate-400 sm:text-xl">{usbTestMode ? 'Scan a card to test without recording attendance' : 'Point scanner at a student QR card'}</p><form onSubmit={sendUsb} className="mt-7 w-full max-w-xl"><label htmlFor="usb-attendance-input" className="sr-only">USB scanner input</label><input id="usb-attendance-input" ref={usbInput} autoFocus readOnly value={usbValue} placeholder="Scanner input appears here automatically" className="w-full rounded-xl border border-slate-600 bg-slate-900 px-4 py-3 text-center font-mono outline-none focus:border-emerald-400" /></form>{usbTestResult && <p className="mt-3 max-w-xl break-all rounded-xl bg-amber-950 px-4 py-3 font-mono text-sm text-amber-200">Received: {usbTestResult}</p>}{actionError && <p className="mt-4 max-w-xl rounded-xl bg-red-950 px-4 py-3 text-red-300" role="alert">{actionError}</p>}{message && !actionError && <p className="mt-4 max-w-xl rounded-xl bg-emerald-950 px-4 py-3 text-emerald-300" role="status">{message}</p>}{!usbActive && !usbLastActivity && <div className="mt-6 max-w-xl rounded-xl border border-amber-700/50 bg-amber-950/40 px-5 py-4 text-sm text-amber-100"><strong className="block text-amber-300">USB scanner not detected — checklist:</strong><span>Connect a keyboard-mode (HID) scanner, configure an Enter/CR suffix, then scan a card. Khmer keyboard layout is supported.</span></div>}</main>
      <aside className="hidden w-80 shrink-0 overflow-y-auto border-l border-slate-700 bg-slate-800 p-5 md:block"><h3 className="font-bold">Attended Today</h3><p className="mt-1 text-xs text-slate-400">{scanHistory.length} scan{scanHistory.length === 1 ? '' : 's'} this session</p><div className="mt-5 space-y-2">{scanHistory.map((record) => { const student = students.find((item) => item.id === record.personId); return <div key={record.personId} className="flex items-center gap-3 rounded-xl bg-slate-700 p-3">{student?.photo ? <img src={student.photo} alt="" className="h-10 w-10 rounded-lg object-cover" /> : <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-600">👤</span>}<div className="min-w-0"><strong className="block truncate text-sm">{student ? displayName(student) : record.personId}</strong><span className="text-xs text-emerald-300">✓ {new Date(record.checkInTime || Date.now()).toLocaleTimeString()}</span></div></div>; })}{!scanHistory.length && <p className="pt-28 text-center text-sm text-slate-500">📋<br />No scans yet</p>}</div></aside></div>
    </div>}
  </section>;
}
