'use client';

import { useEffect, useRef, useState } from 'react';
import { BrowserMultiFormatReader } from '@zxing/library';
import { apiFetch } from '../../lib/api';
import { resolvePluginSourcePath } from '../../lib/plugin-ui-routing';

export default function PluginScanner({ pluginId, source, params, options, onSuccess }: any) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const readerRef = useRef<BrowserMultiFormatReader | null>(null); const lastRef = useRef({ value: '', at: 0 });
  const commandRef = useRef({ fingerprint: '', key: '' });
  const initialContext = Object.fromEntries((options.contextFields || []).map((field: any) => [field.id, field.defaultValue ?? '']));
  const [camera, setCamera] = useState(false); const [stationMode, setStationMode] = useState<'camera' | 'usb' | null>(null); const [value, setValue] = useState(''); const [context, setContext] = useState<Record<string, string | number>>(initialContext); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [clock, setClock] = useState(new Date()); const [history, setHistory] = useState<Array<{ code: string; at: Date }>>([]); const [locationState, setLocationState] = useState('Location not requested');
  useEffect(() => () => { readerRef.current?.reset(); readerRef.current = null; }, []);
  useEffect(() => { const timer = window.setInterval(() => setClock(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!options.autoLocation || !navigator.geolocation) return; setLocationState('Requesting location…'); const id = navigator.geolocation.watchPosition((position) => { setContext((current) => ({ ...current, latitude: position.coords.latitude, longitude: position.coords.longitude })); setLocationState(`Location active · ±${Math.round(position.coords.accuracy)} m`); }, () => setLocationState('Location unavailable — scanner can still submit if policy allows'), { enableHighAccuracy: true, maximumAge: 15000 }); return () => navigator.geolocation.clearWatch(id); }, [options.autoLocation]);
  async function submit(code: string, mode: 'CAMERA' | 'USB') { const clean = code.trim(); if (clean.length < (options.minLength || 1) || clean.length > (options.maxLength || 1000)) return setMessage('Scanned value has an invalid length.'); for (const field of options.contextFields || []) if (field.required && (context[field.id] === '' || context[field.id] === undefined)) return setMessage(`${field.label} is required.`); const now = Date.now(); if (lastRef.current.value === clean && now - lastRef.current.at < (options.debounceMs || 1000)) return; lastRef.current = { value: clean, at: now }; const fingerprint = JSON.stringify([clean, mode, context]); if (commandRef.current.fingerprint !== fingerprint) commandRef.current = { fingerprint, key: globalThis.crypto.randomUUID() }; setBusy(true); setMessage(''); try { const endpoint = `/api/plugin-api/${encodeURIComponent(pluginId)}/${resolvePluginSourcePath(source.path, params)}`; const response = await apiFetch(endpoint, { method: source.method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [options.field]: clean, ...context, mode, clientTimestamp: new Date().toISOString(), idempotencyKey: commandRef.current.key }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.message || 'Scan rejected.'); setMessage(result.idempotentReplay ? 'Scan was already accepted.' : 'Scan accepted.'); setHistory((current) => [{ code: clean.slice(-12), at: new Date() }, ...current].slice(0, 20)); navigator.vibrate?.(100); setValue(''); commandRef.current = { fingerprint: '', key: '' }; await onSuccess(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Scan failed. Retry will safely reuse the same command.'); navigator.vibrate?.([80, 60, 80]); } finally { setBusy(false); } }
  async function startCamera() { setStationMode('camera'); window.setTimeout(async () => { if (!videoRef.current) return; setMessage(''); try { const reader = new BrowserMultiFormatReader(); readerRef.current = reader; setCamera(true); await reader.decodeFromVideoDevice(null, videoRef.current, (result) => { if (result) void submit(result.getText(), 'CAMERA'); }); } catch (cause) { setCamera(false); setMessage(cause instanceof Error ? cause.message : 'Camera is unavailable. Check browser permission and retry.'); } }, 0); }
  function stopCamera() { readerRef.current?.reset(); readerRef.current = null; setCamera(false); }
  function closeStation() { stopCamera(); setStationMode(null); setMessage(''); }
  if (options.station && stationMode) return <div className="fixed inset-0 z-[100] flex flex-col bg-slate-950 text-white"><header className="flex items-center gap-5 border-b border-slate-700 bg-slate-800 px-5 py-4"><button onClick={closeStation} className="font-bold">‹ Back</button><div className="flex-1"><h2 className="font-extrabold">{stationMode === 'camera' ? '📷 Camera' : '🖱️ USB Scanner'} — Staff Attendance</h2><p className="text-xs text-slate-400">{locationState}</p></div><strong className="font-mono text-xl">{clock.toLocaleTimeString()}</strong></header><div className="flex min-h-0 flex-1"><main className="relative flex min-w-0 flex-1 flex-col items-center justify-center">{stationMode === 'camera' ? <><video ref={videoRef} className="absolute inset-0 h-full w-full object-cover" muted playsInline /><div className="pointer-events-none relative h-64 w-64 rounded-3xl border-4 border-emerald-400 shadow-[0_0_0_9999px_rgba(0,0,0,.55)]" /><p className="relative mt-6 rounded-full bg-emerald-600/90 px-6 py-3 font-bold">{camera ? 'Camera ready — scan staff QR code' : 'Starting camera…'}</p></> : <><div className="flex h-40 w-40 items-center justify-center rounded-[2.5rem] border border-emerald-500/30 bg-emerald-950 text-6xl">🖱️</div><h2 className="mt-7 text-4xl font-extrabold">Ready to Scan</h2><p className="mt-3 text-slate-400">Point scanner at a staff QR card</p><form className="mt-8 w-full max-w-xl px-6" onSubmit={(event) => { event.preventDefault(); void submit(value, 'USB'); }}><input autoFocus className="w-full rounded-xl border border-slate-600 bg-slate-900 px-4 py-3 text-center font-mono focus:border-emerald-400" value={value} onChange={(event) => setValue(event.target.value)} autoComplete="off" /></form></>}{message && <p className={`relative mt-5 rounded-xl px-5 py-3 ${message.toLowerCase().includes('accepted') ? 'bg-emerald-700' : 'bg-rose-700'}`} role="status">{message}</p>}</main><aside className="hidden w-80 border-l border-slate-700 bg-slate-800 p-5 md:block"><h3 className="font-bold">Attended Today</h3><div className="mt-5 space-y-2">{history.map((item, index) => <div key={`${item.at.getTime()}-${index}`} className="rounded-xl bg-slate-700 p-3"><strong className="block font-mono text-sm">…{item.code}</strong><span className="text-xs text-emerald-300">✓ {item.at.toLocaleTimeString()}</span></div>)}{!history.length && <p className="pt-32 text-center text-sm text-slate-500">📋<br />No scans yet</p>}</div></aside></div></div>;
  if (options.station) return <section className="card p-6"><h2 className="text-xl font-bold text-slate-900">Staff Attendance Station</h2><p className="mt-1 text-sm text-slate-500">Scan staff ID cards with the camera or a USB scanner. Session and check-in/check-out are selected automatically.</p><div className="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">● {locationState}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><button className="rounded-2xl bg-cyan-600 p-8 text-left text-white shadow-lg" onClick={() => void startCamera()}><span className="text-4xl">📷</span><strong className="mt-3 block text-xl">Open Camera</strong><span className="text-sm text-cyan-100">Scan QR cards using this device</span></button><button className="rounded-2xl bg-slate-900 p-8 text-left text-white shadow-lg" onClick={() => setStationMode('usb')}><span className="text-4xl">🖱️</span><strong className="mt-3 block text-xl">USB Scanner</strong><span className="text-sm text-slate-300">Dedicated keyboard-style scanner station</span></button></div>{message && <p className="mt-4 text-sm" role="status">{message}</p>}</section>;
  return <section className="card max-w-2xl p-5"><h2 className="font-semibold text-slate-800">Scanner</h2>{options.contextFields?.length > 0 && <div className="mt-4 grid gap-3 sm:grid-cols-2">{options.contextFields.map((field: any) => <label key={field.id} className="text-sm font-medium text-slate-700">{field.label}{field.required ? ' *' : ''}{field.type === 'select' ? <select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={context[field.id]} disabled={busy} onChange={(event) => setContext((current) => ({ ...current, [field.id]: event.target.value }))}><option value="">Select…</option>{field.options.map((option: any) => <option key={String(option.value)} value={option.value}>{option.label}</option>)}</select> : <input className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" type={field.type === 'number' ? 'number' : 'text'} value={context[field.id]} disabled={busy} onChange={(event) => setContext((current) => ({ ...current, [field.id]: event.target.value }))} />}</label>)}</div>}{options.modes.includes('keyboard') && <form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); void submit(value, 'USB'); }}><label className="sr-only" htmlFor="plugin-scanner-code">Scan or enter code</label><input id="plugin-scanner-code" autoFocus className="flex-1 rounded-lg border border-slate-300 px-3 py-2 font-mono" value={value} disabled={busy} onChange={(event) => setValue(event.target.value)} placeholder="Scan or enter code, then press Enter" autoComplete="off" /><button className="btn btn-primary" disabled={busy}>Submit</button></form>}{options.modes.includes('camera') && <div className="mt-4"><video ref={videoRef} className={`aspect-video w-full rounded-lg bg-black ${camera ? '' : 'hidden'}`} muted playsInline /><button className="btn btn-secondary mt-2" disabled={busy} onClick={camera ? stopCamera : startCamera}>{camera ? 'Stop camera' : 'Start camera'}</button></div>}{message && <p className="mt-3 text-sm" role="status" aria-live="polite">{message}</p>}</section>;
}
